// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_DBCACHE_GENERICBOSON_ZOZO_H_
#define FLATBUFFERS_GENERATED_DBCACHE_GENERICBOSON_ZOZO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "CharacterInfo_generated.h"
#include "Constant_generated.h"
#include "ServerInfo_generated.h"

namespace GenericBoson {
namespace Zozo {

struct LoginDBReq;
struct LoginDBReqBuilder;

struct LoginDBAck;
struct LoginDBAckBuilder;

struct DBCacheMessage;
struct DBCacheMessageBuilder;

enum DBCachePayload : uint8_t {
  DBCachePayload_NONE = 0,
  DBCachePayload_LoginDBReq = 1,
  DBCachePayload_LoginDBAck = 2,
  DBCachePayload_MIN = DBCachePayload_NONE,
  DBCachePayload_MAX = DBCachePayload_LoginDBAck
};

inline const DBCachePayload (&EnumValuesDBCachePayload())[3] {
  static const DBCachePayload values[] = {
    DBCachePayload_NONE,
    DBCachePayload_LoginDBReq,
    DBCachePayload_LoginDBAck
  };
  return values;
}

inline const char * const *EnumNamesDBCachePayload() {
  static const char * const names[4] = {
    "NONE",
    "LoginDBReq",
    "LoginDBAck",
    nullptr
  };
  return names;
}

inline const char *EnumNameDBCachePayload(DBCachePayload e) {
  if (::flatbuffers::IsOutRange(e, DBCachePayload_NONE, DBCachePayload_LoginDBAck)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesDBCachePayload()[index];
}

template<typename T> struct DBCachePayloadTraits {
  static const DBCachePayload enum_value = DBCachePayload_NONE;
};

template<> struct DBCachePayloadTraits<GenericBoson::Zozo::LoginDBReq> {
  static const DBCachePayload enum_value = DBCachePayload_LoginDBReq;
};

template<> struct DBCachePayloadTraits<GenericBoson::Zozo::LoginDBAck> {
  static const DBCachePayload enum_value = DBCachePayload_LoginDBAck;
};

bool VerifyDBCachePayload(::flatbuffers::Verifier &verifier, const void *obj, DBCachePayload type);
bool VerifyDBCachePayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct LoginDBReq FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginDBReqBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACCOUNT = 4
  };
  const ::flatbuffers::String *account() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ACCOUNT);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACCOUNT) &&
           verifier.VerifyString(account()) &&
           verifier.EndTable();
  }
};

struct LoginDBReqBuilder {
  typedef LoginDBReq Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_account(::flatbuffers::Offset<::flatbuffers::String> account) {
    fbb_.AddOffset(LoginDBReq::VT_ACCOUNT, account);
  }
  explicit LoginDBReqBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginDBReq> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginDBReq>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginDBReq> CreateLoginDBReq(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> account = 0) {
  LoginDBReqBuilder builder_(_fbb);
  builder_.add_account(account);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LoginDBReq> CreateLoginDBReqDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *account = nullptr) {
  auto account__ = account ? _fbb.CreateString(account) : 0;
  return GenericBoson::Zozo::CreateLoginDBReq(
      _fbb,
      account__);
}

struct LoginDBAck FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LoginDBAckBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_RESULT_CODE = 4,
    VT_SERVER_INFOS = 6,
    VT_CHARACTERS = 8,
    VT_PASSWORD = 10
  };
  GenericBoson::Zozo::ResultCode result_code() const {
    return static_cast<GenericBoson::Zozo::ResultCode>(GetField<uint32_t>(VT_RESULT_CODE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GenericBoson::Zozo::ServerInfo>> *server_infos() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GenericBoson::Zozo::ServerInfo>> *>(VT_SERVER_INFOS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<GenericBoson::Zozo::CharacterInfo>> *characters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<GenericBoson::Zozo::CharacterInfo>> *>(VT_CHARACTERS);
  }
  const ::flatbuffers::String *password() const {
    return GetPointer<const ::flatbuffers::String *>(VT_PASSWORD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_RESULT_CODE, 4) &&
           VerifyOffset(verifier, VT_SERVER_INFOS) &&
           verifier.VerifyVector(server_infos()) &&
           verifier.VerifyVectorOfTables(server_infos()) &&
           VerifyOffset(verifier, VT_CHARACTERS) &&
           verifier.VerifyVector(characters()) &&
           verifier.VerifyVectorOfTables(characters()) &&
           VerifyOffset(verifier, VT_PASSWORD) &&
           verifier.VerifyString(password()) &&
           verifier.EndTable();
  }
};

struct LoginDBAckBuilder {
  typedef LoginDBAck Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_result_code(GenericBoson::Zozo::ResultCode result_code) {
    fbb_.AddElement<uint32_t>(LoginDBAck::VT_RESULT_CODE, static_cast<uint32_t>(result_code), 0);
  }
  void add_server_infos(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GenericBoson::Zozo::ServerInfo>>> server_infos) {
    fbb_.AddOffset(LoginDBAck::VT_SERVER_INFOS, server_infos);
  }
  void add_characters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GenericBoson::Zozo::CharacterInfo>>> characters) {
    fbb_.AddOffset(LoginDBAck::VT_CHARACTERS, characters);
  }
  void add_password(::flatbuffers::Offset<::flatbuffers::String> password) {
    fbb_.AddOffset(LoginDBAck::VT_PASSWORD, password);
  }
  explicit LoginDBAckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LoginDBAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LoginDBAck>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LoginDBAck> CreateLoginDBAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GenericBoson::Zozo::ResultCode result_code = GenericBoson::Zozo::ResultCode_Success,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GenericBoson::Zozo::ServerInfo>>> server_infos = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<GenericBoson::Zozo::CharacterInfo>>> characters = 0,
    ::flatbuffers::Offset<::flatbuffers::String> password = 0) {
  LoginDBAckBuilder builder_(_fbb);
  builder_.add_password(password);
  builder_.add_characters(characters);
  builder_.add_server_infos(server_infos);
  builder_.add_result_code(result_code);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<LoginDBAck> CreateLoginDBAckDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GenericBoson::Zozo::ResultCode result_code = GenericBoson::Zozo::ResultCode_Success,
    const std::vector<::flatbuffers::Offset<GenericBoson::Zozo::ServerInfo>> *server_infos = nullptr,
    const std::vector<::flatbuffers::Offset<GenericBoson::Zozo::CharacterInfo>> *characters = nullptr,
    const char *password = nullptr) {
  auto server_infos__ = server_infos ? _fbb.CreateVector<::flatbuffers::Offset<GenericBoson::Zozo::ServerInfo>>(*server_infos) : 0;
  auto characters__ = characters ? _fbb.CreateVector<::flatbuffers::Offset<GenericBoson::Zozo::CharacterInfo>>(*characters) : 0;
  auto password__ = password ? _fbb.CreateString(password) : 0;
  return GenericBoson::Zozo::CreateLoginDBAck(
      _fbb,
      result_code,
      server_infos__,
      characters__,
      password__);
}

struct DBCacheMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef DBCacheMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  GenericBoson::Zozo::DBCachePayload payload_type() const {
    return static_cast<GenericBoson::Zozo::DBCachePayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const GenericBoson::Zozo::LoginDBReq *payload_as_LoginDBReq() const {
    return payload_type() == GenericBoson::Zozo::DBCachePayload_LoginDBReq ? static_cast<const GenericBoson::Zozo::LoginDBReq *>(payload()) : nullptr;
  }
  const GenericBoson::Zozo::LoginDBAck *payload_as_LoginDBAck() const {
    return payload_type() == GenericBoson::Zozo::DBCachePayload_LoginDBAck ? static_cast<const GenericBoson::Zozo::LoginDBAck *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyDBCachePayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const GenericBoson::Zozo::LoginDBReq *DBCacheMessage::payload_as<GenericBoson::Zozo::LoginDBReq>() const {
  return payload_as_LoginDBReq();
}

template<> inline const GenericBoson::Zozo::LoginDBAck *DBCacheMessage::payload_as<GenericBoson::Zozo::LoginDBAck>() const {
  return payload_as_LoginDBAck();
}

struct DBCacheMessageBuilder {
  typedef DBCacheMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(GenericBoson::Zozo::DBCachePayload payload_type) {
    fbb_.AddElement<uint8_t>(DBCacheMessage::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(DBCacheMessage::VT_PAYLOAD, payload);
  }
  explicit DBCacheMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<DBCacheMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<DBCacheMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<DBCacheMessage> CreateDBCacheMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GenericBoson::Zozo::DBCachePayload payload_type = GenericBoson::Zozo::DBCachePayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  DBCacheMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyDBCachePayload(::flatbuffers::Verifier &verifier, const void *obj, DBCachePayload type) {
  switch (type) {
    case DBCachePayload_NONE: {
      return true;
    }
    case DBCachePayload_LoginDBReq: {
      auto ptr = reinterpret_cast<const GenericBoson::Zozo::LoginDBReq *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case DBCachePayload_LoginDBAck: {
      auto ptr = reinterpret_cast<const GenericBoson::Zozo::LoginDBAck *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyDBCachePayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyDBCachePayload(
        verifier,  values->Get(i), types->GetEnum<DBCachePayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const GenericBoson::Zozo::DBCacheMessage *GetDBCacheMessage(const void *buf) {
  return ::flatbuffers::GetRoot<GenericBoson::Zozo::DBCacheMessage>(buf);
}

inline const GenericBoson::Zozo::DBCacheMessage *GetSizePrefixedDBCacheMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GenericBoson::Zozo::DBCacheMessage>(buf);
}

inline bool VerifyDBCacheMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GenericBoson::Zozo::DBCacheMessage>(nullptr);
}

inline bool VerifySizePrefixedDBCacheMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GenericBoson::Zozo::DBCacheMessage>(nullptr);
}

inline void FinishDBCacheMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GenericBoson::Zozo::DBCacheMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedDBCacheMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GenericBoson::Zozo::DBCacheMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Zozo
}  // namespace GenericBoson

#endif  // FLATBUFFERS_GENERATED_DBCACHE_GENERICBOSON_ZOZO_H_
