// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_INTERNALCONSTANT_GENERICBOSON_ZOZO_H_
#define FLATBUFFERS_GENERATED_INTERNALCONSTANT_GENERICBOSON_ZOZO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace GenericBoson {
namespace Zozo {

enum InternalResultCode : uint32_t {
  InternalResultCode_Success = 0,
  InternalResultCode_MIN = InternalResultCode_Success,
  InternalResultCode_MAX = InternalResultCode_Success
};

inline const InternalResultCode (&EnumValuesInternalResultCode())[1] {
  static const InternalResultCode values[] = {
    InternalResultCode_Success
  };
  return values;
}

inline const char * const *EnumNamesInternalResultCode() {
  static const char * const names[2] = {
    "Success",
    nullptr
  };
  return names;
}

inline const char *EnumNameInternalResultCode(InternalResultCode e) {
  if (::flatbuffers::IsOutRange(e, InternalResultCode_Success, InternalResultCode_Success)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesInternalResultCode()[index];
}

}  // namespace Zozo
}  // namespace GenericBoson

#endif  // FLATBUFFERS_GENERATED_INTERNALCONSTANT_GENERICBOSON_ZOZO_H_
