// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_LOBBYGAME_GENERICBOSON_ZOZO_H_
#define FLATBUFFERS_GENERATED_LOBBYGAME_GENERICBOSON_ZOZO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Constant_generated.h"
#include "ServerInfo_generated.h"

namespace GenericBoson {
namespace Zozo {

struct RegisterReq;
struct RegisterReqBuilder;

struct RegisterAck;
struct RegisterAckBuilder;

struct LobbyGameMessage;
struct LobbyGameMessageBuilder;

enum LobbyGamePayload : uint8_t {
  LobbyGamePayload_NONE = 0,
  LobbyGamePayload_RegisterReq = 1,
  LobbyGamePayload_RegisterAck = 2,
  LobbyGamePayload_MIN = LobbyGamePayload_NONE,
  LobbyGamePayload_MAX = LobbyGamePayload_RegisterAck
};

inline const LobbyGamePayload (&EnumValuesLobbyGamePayload())[3] {
  static const LobbyGamePayload values[] = {
    LobbyGamePayload_NONE,
    LobbyGamePayload_RegisterReq,
    LobbyGamePayload_RegisterAck
  };
  return values;
}

inline const char * const *EnumNamesLobbyGamePayload() {
  static const char * const names[4] = {
    "NONE",
    "RegisterReq",
    "RegisterAck",
    nullptr
  };
  return names;
}

inline const char *EnumNameLobbyGamePayload(LobbyGamePayload e) {
  if (::flatbuffers::IsOutRange(e, LobbyGamePayload_NONE, LobbyGamePayload_RegisterAck)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesLobbyGamePayload()[index];
}

template<typename T> struct LobbyGamePayloadTraits {
  static const LobbyGamePayload enum_value = LobbyGamePayload_NONE;
};

template<> struct LobbyGamePayloadTraits<GenericBoson::Zozo::RegisterReq> {
  static const LobbyGamePayload enum_value = LobbyGamePayload_RegisterReq;
};

template<> struct LobbyGamePayloadTraits<GenericBoson::Zozo::RegisterAck> {
  static const LobbyGamePayload enum_value = LobbyGamePayload_RegisterAck;
};

bool VerifyLobbyGamePayload(::flatbuffers::Verifier &verifier, const void *obj, LobbyGamePayload type);
bool VerifyLobbyGamePayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct RegisterReq FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RegisterReqBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SERVER_NAME = 4
  };
  const ::flatbuffers::String *server_name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_SERVER_NAME);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_SERVER_NAME) &&
           verifier.VerifyString(server_name()) &&
           verifier.EndTable();
  }
};

struct RegisterReqBuilder {
  typedef RegisterReq Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_server_name(::flatbuffers::Offset<::flatbuffers::String> server_name) {
    fbb_.AddOffset(RegisterReq::VT_SERVER_NAME, server_name);
  }
  explicit RegisterReqBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RegisterReq> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RegisterReq>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RegisterReq> CreateRegisterReq(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> server_name = 0) {
  RegisterReqBuilder builder_(_fbb);
  builder_.add_server_name(server_name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RegisterReq> CreateRegisterReqDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *server_name = nullptr) {
  auto server_name__ = server_name ? _fbb.CreateString(server_name) : 0;
  return GenericBoson::Zozo::CreateRegisterReq(
      _fbb,
      server_name__);
}

struct RegisterAck FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RegisterAckBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TOKEN = 4,
    VT_RESULT_CODE = 6
  };
  const ::flatbuffers::String *token() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TOKEN);
  }
  GenericBoson::Zozo::ResultCode result_code() const {
    return static_cast<GenericBoson::Zozo::ResultCode>(GetField<uint32_t>(VT_RESULT_CODE, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TOKEN) &&
           verifier.VerifyString(token()) &&
           VerifyField<uint32_t>(verifier, VT_RESULT_CODE, 4) &&
           verifier.EndTable();
  }
};

struct RegisterAckBuilder {
  typedef RegisterAck Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_token(::flatbuffers::Offset<::flatbuffers::String> token) {
    fbb_.AddOffset(RegisterAck::VT_TOKEN, token);
  }
  void add_result_code(GenericBoson::Zozo::ResultCode result_code) {
    fbb_.AddElement<uint32_t>(RegisterAck::VT_RESULT_CODE, static_cast<uint32_t>(result_code), 0);
  }
  explicit RegisterAckBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<RegisterAck> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<RegisterAck>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<RegisterAck> CreateRegisterAck(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> token = 0,
    GenericBoson::Zozo::ResultCode result_code = GenericBoson::Zozo::ResultCode_Success) {
  RegisterAckBuilder builder_(_fbb);
  builder_.add_result_code(result_code);
  builder_.add_token(token);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<RegisterAck> CreateRegisterAckDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *token = nullptr,
    GenericBoson::Zozo::ResultCode result_code = GenericBoson::Zozo::ResultCode_Success) {
  auto token__ = token ? _fbb.CreateString(token) : 0;
  return GenericBoson::Zozo::CreateRegisterAck(
      _fbb,
      token__,
      result_code);
}

struct LobbyGameMessage FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef LobbyGameMessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PAYLOAD_TYPE = 4,
    VT_PAYLOAD = 6
  };
  GenericBoson::Zozo::LobbyGamePayload payload_type() const {
    return static_cast<GenericBoson::Zozo::LobbyGamePayload>(GetField<uint8_t>(VT_PAYLOAD_TYPE, 0));
  }
  const void *payload() const {
    return GetPointer<const void *>(VT_PAYLOAD);
  }
  template<typename T> const T *payload_as() const;
  const GenericBoson::Zozo::RegisterReq *payload_as_RegisterReq() const {
    return payload_type() == GenericBoson::Zozo::LobbyGamePayload_RegisterReq ? static_cast<const GenericBoson::Zozo::RegisterReq *>(payload()) : nullptr;
  }
  const GenericBoson::Zozo::RegisterAck *payload_as_RegisterAck() const {
    return payload_type() == GenericBoson::Zozo::LobbyGamePayload_RegisterAck ? static_cast<const GenericBoson::Zozo::RegisterAck *>(payload()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_PAYLOAD_TYPE, 1) &&
           VerifyOffset(verifier, VT_PAYLOAD) &&
           VerifyLobbyGamePayload(verifier, payload(), payload_type()) &&
           verifier.EndTable();
  }
};

template<> inline const GenericBoson::Zozo::RegisterReq *LobbyGameMessage::payload_as<GenericBoson::Zozo::RegisterReq>() const {
  return payload_as_RegisterReq();
}

template<> inline const GenericBoson::Zozo::RegisterAck *LobbyGameMessage::payload_as<GenericBoson::Zozo::RegisterAck>() const {
  return payload_as_RegisterAck();
}

struct LobbyGameMessageBuilder {
  typedef LobbyGameMessage Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_payload_type(GenericBoson::Zozo::LobbyGamePayload payload_type) {
    fbb_.AddElement<uint8_t>(LobbyGameMessage::VT_PAYLOAD_TYPE, static_cast<uint8_t>(payload_type), 0);
  }
  void add_payload(::flatbuffers::Offset<void> payload) {
    fbb_.AddOffset(LobbyGameMessage::VT_PAYLOAD, payload);
  }
  explicit LobbyGameMessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<LobbyGameMessage> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<LobbyGameMessage>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<LobbyGameMessage> CreateLobbyGameMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    GenericBoson::Zozo::LobbyGamePayload payload_type = GenericBoson::Zozo::LobbyGamePayload_NONE,
    ::flatbuffers::Offset<void> payload = 0) {
  LobbyGameMessageBuilder builder_(_fbb);
  builder_.add_payload(payload);
  builder_.add_payload_type(payload_type);
  return builder_.Finish();
}

inline bool VerifyLobbyGamePayload(::flatbuffers::Verifier &verifier, const void *obj, LobbyGamePayload type) {
  switch (type) {
    case LobbyGamePayload_NONE: {
      return true;
    }
    case LobbyGamePayload_RegisterReq: {
      auto ptr = reinterpret_cast<const GenericBoson::Zozo::RegisterReq *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case LobbyGamePayload_RegisterAck: {
      auto ptr = reinterpret_cast<const GenericBoson::Zozo::RegisterAck *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyLobbyGamePayloadVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyLobbyGamePayload(
        verifier,  values->Get(i), types->GetEnum<LobbyGamePayload>(i))) {
      return false;
    }
  }
  return true;
}

inline const GenericBoson::Zozo::LobbyGameMessage *GetLobbyGameMessage(const void *buf) {
  return ::flatbuffers::GetRoot<GenericBoson::Zozo::LobbyGameMessage>(buf);
}

inline const GenericBoson::Zozo::LobbyGameMessage *GetSizePrefixedLobbyGameMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<GenericBoson::Zozo::LobbyGameMessage>(buf);
}

inline bool VerifyLobbyGameMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<GenericBoson::Zozo::LobbyGameMessage>(nullptr);
}

inline bool VerifySizePrefixedLobbyGameMessageBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<GenericBoson::Zozo::LobbyGameMessage>(nullptr);
}

inline void FinishLobbyGameMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GenericBoson::Zozo::LobbyGameMessage> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedLobbyGameMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<GenericBoson::Zozo::LobbyGameMessage> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Zozo
}  // namespace GenericBoson

#endif  // FLATBUFFERS_GENERATED_LOBBYGAME_GENERICBOSON_ZOZO_H_
