//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FlatBuffers.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFlatBuffersListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class FlatBuffersBaseListener : IFlatBuffersListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.schema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSchema([NotNull] FlatBuffersParser.SchemaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.schema"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSchema([NotNull] FlatBuffersParser.SchemaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInclude([NotNull] FlatBuffersParser.IncludeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInclude([NotNull] FlatBuffersParser.IncludeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.namespace_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNamespace_decl([NotNull] FlatBuffersParser.Namespace_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.namespace_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNamespace_decl([NotNull] FlatBuffersParser.Namespace_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.attribute_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAttribute_decl([NotNull] FlatBuffersParser.Attribute_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.attribute_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAttribute_decl([NotNull] FlatBuffersParser.Attribute_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.type_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_decl([NotNull] FlatBuffersParser.Type_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.type_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_decl([NotNull] FlatBuffersParser.Type_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.enum_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnum_decl([NotNull] FlatBuffersParser.Enum_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.enum_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnum_decl([NotNull] FlatBuffersParser.Enum_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.root_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRoot_decl([NotNull] FlatBuffersParser.Root_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.root_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRoot_decl([NotNull] FlatBuffersParser.Root_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.field_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_decl([NotNull] FlatBuffersParser.Field_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.field_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_decl([NotNull] FlatBuffersParser.Field_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.rpc_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRpc_decl([NotNull] FlatBuffersParser.Rpc_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.rpc_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRpc_decl([NotNull] FlatBuffersParser.Rpc_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.rpc_method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRpc_method([NotNull] FlatBuffersParser.Rpc_methodContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.rpc_method"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRpc_method([NotNull] FlatBuffersParser.Rpc_methodContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType_([NotNull] FlatBuffersParser.Type_Context context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.type_"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType_([NotNull] FlatBuffersParser.Type_Context context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.enumval_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEnumval_decl([NotNull] FlatBuffersParser.Enumval_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.enumval_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEnumval_decl([NotNull] FlatBuffersParser.Enumval_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.metadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMetadata([NotNull] FlatBuffersParser.MetadataContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.metadata"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMetadata([NotNull] FlatBuffersParser.MetadataContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.scalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterScalar([NotNull] FlatBuffersParser.ScalarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.scalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitScalar([NotNull] FlatBuffersParser.ScalarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObject([NotNull] FlatBuffersParser.ObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObject([NotNull] FlatBuffersParser.ObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.single_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSingle_value([NotNull] FlatBuffersParser.Single_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.single_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSingle_value([NotNull] FlatBuffersParser.Single_valueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] FlatBuffersParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] FlatBuffersParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.file_extension_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile_extension_decl([NotNull] FlatBuffersParser.File_extension_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.file_extension_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile_extension_decl([NotNull] FlatBuffersParser.File_extension_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.file_identifier_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile_identifier_decl([NotNull] FlatBuffersParser.File_identifier_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.file_identifier_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile_identifier_decl([NotNull] FlatBuffersParser.File_identifier_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.commasep_enumval_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommasep_enumval_decl([NotNull] FlatBuffersParser.Commasep_enumval_declContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.commasep_enumval_decl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommasep_enumval_decl([NotNull] FlatBuffersParser.Commasep_enumval_declContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.commasep_metadata_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommasep_metadata_item([NotNull] FlatBuffersParser.Commasep_metadata_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.commasep_metadata_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommasep_metadata_item([NotNull] FlatBuffersParser.Commasep_metadata_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.commasep_object_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommasep_object_item([NotNull] FlatBuffersParser.Commasep_object_itemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.commasep_object_item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommasep_object_item([NotNull] FlatBuffersParser.Commasep_object_itemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="FlatBuffersParser.commasep_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommasep_value([NotNull] FlatBuffersParser.Commasep_valueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FlatBuffersParser.commasep_value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommasep_value([NotNull] FlatBuffersParser.Commasep_valueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
