//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from FlatBuffers.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class FlatBuffersParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, BooleanConstant=45, 
		Ident=46, IntegerConstant=47, FloatConstant=48, StringConstant=49, WS=50;
	public const int
		RULE_schema = 0, RULE_include = 1, RULE_namespace_decl = 2, RULE_attribute_decl = 3, 
		RULE_type_decl = 4, RULE_enum_decl = 5, RULE_root_decl = 6, RULE_field_decl = 7, 
		RULE_rpc_decl = 8, RULE_rpc_method = 9, RULE_type_ = 10, RULE_enumval_decl = 11, 
		RULE_metadata = 12, RULE_scalar = 13, RULE_object = 14, RULE_single_value = 15, 
		RULE_value = 16, RULE_file_extension_decl = 17, RULE_file_identifier_decl = 18, 
		RULE_commasep_enumval_decl = 19, RULE_commasep_metadata_item = 20, RULE_commasep_object_item = 21, 
		RULE_commasep_value = 22;
	public static readonly string[] ruleNames = {
		"schema", "include", "namespace_decl", "attribute_decl", "type_decl", 
		"enum_decl", "root_decl", "field_decl", "rpc_decl", "rpc_method", "type_", 
		"enumval_decl", "metadata", "scalar", "object", "single_value", "value", 
		"file_extension_decl", "file_identifier_decl", "commasep_enumval_decl", 
		"commasep_metadata_item", "commasep_object_item", "commasep_value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'include'", "';'", "'namespace'", "'.'", "'attribute'", "'table'", 
		"'struct'", "'{'", "'}'", "'enum'", "':'", "'union'", "'root_type'", "'='", 
		"'rpc_service'", "'('", "')'", "'bool'", "'byte'", "'ubyte'", "'short'", 
		"'ushort'", "'int'", "'uint'", "'float'", "'long'", "'ulong'", "'double'", 
		"'int8'", "'uint8'", "'int16'", "'uint16'", "'int32'", "'uint32'", "'int64'", 
		"'uint64'", "'float32'", "'float64'", "'string'", "'['", "']'", "'file_extension'", 
		"'file_identifier'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "BooleanConstant", 
		"Ident", "IntegerConstant", "FloatConstant", "StringConstant", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "FlatBuffers.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static FlatBuffersParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public FlatBuffersParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public FlatBuffersParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class SchemaContext : ParserRuleContext {
		public FlatCacheGenerator.FlatBufferTree output;
		public IncludeContext includeOne;
		public Namespace_declContext namespaceOne;
		public Type_declContext typeOne;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(FlatBuffersParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Enum_declContext[] enum_decl() {
			return GetRuleContexts<Enum_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enum_declContext enum_decl(int i) {
			return GetRuleContext<Enum_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Root_declContext[] root_decl() {
			return GetRuleContexts<Root_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Root_declContext root_decl(int i) {
			return GetRuleContext<Root_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public File_extension_declContext[] file_extension_decl() {
			return GetRuleContexts<File_extension_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public File_extension_declContext file_extension_decl(int i) {
			return GetRuleContext<File_extension_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public File_identifier_declContext[] file_identifier_decl() {
			return GetRuleContexts<File_identifier_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public File_identifier_declContext file_identifier_decl(int i) {
			return GetRuleContext<File_identifier_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Attribute_declContext[] attribute_decl() {
			return GetRuleContexts<Attribute_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Attribute_declContext attribute_decl(int i) {
			return GetRuleContext<Attribute_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Rpc_declContext[] rpc_decl() {
			return GetRuleContexts<Rpc_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Rpc_declContext rpc_decl(int i) {
			return GetRuleContext<Rpc_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext[] @object() {
			return GetRuleContexts<ObjectContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object(int i) {
			return GetRuleContext<ObjectContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public IncludeContext[] include() {
			return GetRuleContexts<IncludeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IncludeContext include(int i) {
			return GetRuleContext<IncludeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Namespace_declContext[] namespace_decl() {
			return GetRuleContexts<Namespace_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Namespace_declContext namespace_decl(int i) {
			return GetRuleContext<Namespace_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_declContext[] type_decl() {
			return GetRuleContexts<Type_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_declContext type_decl(int i) {
			return GetRuleContext<Type_declContext>(i);
		}
		public SchemaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_schema; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterSchema(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitSchema(this);
		}
	}

	[RuleVersion(0)]
	public SchemaContext schema() {
		SchemaContext _localctx = new SchemaContext(Context, State);
		EnterRule(_localctx, 0, RULE_schema);
		 _localctx.output =  new FlatCacheGenerator.FlatBufferTree(); 
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 51;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 46;
				_localctx.includeOne = include();
				 _localctx.output =  _localctx.includeOne.output; 
				}
				}
				State = 53;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 69;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 13194139579880L) != 0)) {
				{
				State = 67;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__2:
					{
					State = 54;
					_localctx.namespaceOne = namespace_decl();
					 _localctx.output.m_namespaces.Add(_localctx.namespaceOne.output); 
					}
					break;
				case T__5:
				case T__6:
					{
					State = 57;
					_localctx.typeOne = type_decl();
					 _localctx.output.m_types.Add(_localctx.typeOne.output); 
					}
					break;
				case T__9:
				case T__11:
					{
					State = 60;
					enum_decl();
					}
					break;
				case T__12:
					{
					State = 61;
					root_decl();
					}
					break;
				case T__41:
					{
					State = 62;
					file_extension_decl();
					}
					break;
				case T__42:
					{
					State = 63;
					file_identifier_decl();
					}
					break;
				case T__4:
					{
					State = 64;
					attribute_decl();
					}
					break;
				case T__14:
					{
					State = 65;
					rpc_decl();
					}
					break;
				case T__7:
					{
					State = 66;
					@object();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 71;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 72;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IncludeContext : ParserRuleContext {
		public string output;
		public IToken stringConstantOne;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public IncludeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_include; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterInclude(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitInclude(this);
		}
	}

	[RuleVersion(0)]
	public IncludeContext include() {
		IncludeContext _localctx = new IncludeContext(Context, State);
		EnterRule(_localctx, 2, RULE_include);
		 _localctx.output =  ""; 
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			Match(T__0);
			State = 75;
			_localctx.stringConstantOne = Match(StringConstant);
			 _localctx.output += (_localctx.stringConstantOne!=null?_localctx.stringConstantOne.Text:null); 
			State = 77;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Namespace_declContext : ParserRuleContext {
		public string output;
		public IToken identFirst;
		public IToken identLeft;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Ident() { return GetTokens(FlatBuffersParser.Ident); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident(int i) {
			return GetToken(FlatBuffersParser.Ident, i);
		}
		public Namespace_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespace_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterNamespace_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitNamespace_decl(this);
		}
	}

	[RuleVersion(0)]
	public Namespace_declContext namespace_decl() {
		Namespace_declContext _localctx = new Namespace_declContext(Context, State);
		EnterRule(_localctx, 4, RULE_namespace_decl);
		 _localctx.output =  ""; 
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 79;
			Match(T__2);
			State = 80;
			_localctx.identFirst = Match(Ident);
			 _localctx.output += (_localctx.identFirst!=null?_localctx.identFirst.Text:null); 
			State = 87;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__3) {
				{
				{
				State = 82;
				Match(T__3);
				State = 83;
				_localctx.identLeft = Match(Ident);
				 _localctx.output += (_localctx.identLeft!=null?_localctx.identLeft.Text:null); 
				}
				}
				State = 89;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 90;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Attribute_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public Attribute_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribute_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterAttribute_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitAttribute_decl(this);
		}
	}

	[RuleVersion(0)]
	public Attribute_declContext attribute_decl() {
		Attribute_declContext _localctx = new Attribute_declContext(Context, State);
		EnterRule(_localctx, 6, RULE_attribute_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(T__4);
			State = 93;
			_la = TokenStream.LA(1);
			if ( !(_la==Ident || _la==StringConstant) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 94;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_declContext : ParserRuleContext {
		public FlatCacheGenerator.FlatBufferType output;
		public IToken identOne;
		public Field_declContext fieldOne;
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Field_declContext[] field_decl() {
			return GetRuleContexts<Field_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Field_declContext field_decl(int i) {
			return GetRuleContext<Field_declContext>(i);
		}
		public Type_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterType_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitType_decl(this);
		}
	}

	[RuleVersion(0)]
	public Type_declContext type_decl() {
		Type_declContext _localctx = new Type_declContext(Context, State);
		EnterRule(_localctx, 8, RULE_type_decl);
		 _localctx.output =  new FlatCacheGenerator.FlatBufferType(); 
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__5:
				{
				State = 96;
				Match(T__5);
				 _localctx.output.m_kind = TypeKind.Table; 
				}
				break;
			case T__6:
				{
				State = 98;
				Match(T__6);
				 _localctx.output.m_kind = TypeKind.Struct; 
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 102;
			_localctx.identOne = Match(Ident);
			  _localctx.output.m_name = (_localctx.identOne!=null?_localctx.identOne.Text:null); 
			State = 104;
			metadata();
			State = 105;
			Match(T__7);
			State = 109;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 106;
				_localctx.fieldOne = field_decl();
				 _localctx.output.m_fields.Add(_localctx.fieldOne.output); 
				}
				}
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Ident );
			State = 113;
			Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Enum_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Commasep_enumval_declContext commasep_enumval_decl() {
			return GetRuleContext<Commasep_enumval_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		public Enum_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enum_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterEnum_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitEnum_decl(this);
		}
	}

	[RuleVersion(0)]
	public Enum_declContext enum_decl() {
		Enum_declContext _localctx = new Enum_declContext(Context, State);
		EnterRule(_localctx, 10, RULE_enum_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 121;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__9:
				{
				State = 115;
				Match(T__9);
				State = 116;
				Match(Ident);
				State = 117;
				Match(T__10);
				State = 118;
				type_();
				}
				break;
			case T__11:
				{
				State = 119;
				Match(T__11);
				State = 120;
				Match(Ident);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 123;
			metadata();
			State = 124;
			Match(T__7);
			State = 125;
			commasep_enumval_decl();
			State = 126;
			Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Root_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		public Root_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_root_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterRoot_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitRoot_decl(this);
		}
	}

	[RuleVersion(0)]
	public Root_declContext root_decl() {
		Root_declContext _localctx = new Root_declContext(Context, State);
		EnterRule(_localctx, 12, RULE_root_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128;
			Match(T__12);
			State = 129;
			Match(Ident);
			State = 130;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Field_declContext : ParserRuleContext {
		public FlatCacheGenerator.FlatBufferField output;
		public IToken identOne;
		public Type_Context typeOne;
		public ScalarContext scalarOne;
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ScalarContext scalar() {
			return GetRuleContext<ScalarContext>(0);
		}
		public Field_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterField_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitField_decl(this);
		}
	}

	[RuleVersion(0)]
	public Field_declContext field_decl() {
		Field_declContext _localctx = new Field_declContext(Context, State);
		EnterRule(_localctx, 14, RULE_field_decl);
		 _localctx.output =  new FlatCacheGenerator.FlatBufferField(); 
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 132;
			_localctx.identOne = Match(Ident);
			 _localctx.output.m_name = (_localctx.identOne!=null?_localctx.identOne.Text:null); 
			State = 134;
			Match(T__10);
			State = 135;
			_localctx.typeOne = type_();
			 _localctx.output.m_type = (_localctx.typeOne!=null?TokenStream.GetText(_localctx.typeOne.Start,_localctx.typeOne.Stop):null); 
			State = 141;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__13) {
				{
				State = 137;
				Match(T__13);
				State = 138;
				_localctx.scalarOne = scalar();
				 _localctx.output.m_defaultValue = (_localctx.scalarOne!=null?TokenStream.GetText(_localctx.scalarOne.Start,_localctx.scalarOne.Stop):null); 
				}
			}

			State = 143;
			metadata();
			State = 144;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rpc_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Rpc_methodContext[] rpc_method() {
			return GetRuleContexts<Rpc_methodContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Rpc_methodContext rpc_method(int i) {
			return GetRuleContext<Rpc_methodContext>(i);
		}
		public Rpc_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rpc_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterRpc_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitRpc_decl(this);
		}
	}

	[RuleVersion(0)]
	public Rpc_declContext rpc_decl() {
		Rpc_declContext _localctx = new Rpc_declContext(Context, State);
		EnterRule(_localctx, 16, RULE_rpc_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			Match(T__14);
			State = 147;
			Match(Ident);
			State = 148;
			Match(T__7);
			State = 150;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 149;
				rpc_method();
				}
				}
				State = 152;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Ident );
			State = 154;
			Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rpc_methodContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Ident() { return GetTokens(FlatBuffersParser.Ident); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident(int i) {
			return GetToken(FlatBuffersParser.Ident, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		public Rpc_methodContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rpc_method; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterRpc_method(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitRpc_method(this);
		}
	}

	[RuleVersion(0)]
	public Rpc_methodContext rpc_method() {
		Rpc_methodContext _localctx = new Rpc_methodContext(Context, State);
		EnterRule(_localctx, 18, RULE_rpc_method);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156;
			Match(Ident);
			State = 157;
			Match(T__15);
			State = 158;
			Match(Ident);
			State = 159;
			Match(T__16);
			State = 160;
			Match(T__10);
			State = 161;
			Match(Ident);
			State = 162;
			metadata();
			State = 163;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		public Type_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterType_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitType_(this);
		}
	}

	[RuleVersion(0)]
	public Type_Context type_() {
		Type_Context _localctx = new Type_Context(Context, State);
		EnterRule(_localctx, 20, RULE_type_);
		try {
			State = 192;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__17:
				EnterOuterAlt(_localctx, 1);
				{
				State = 165;
				Match(T__17);
				}
				break;
			case T__18:
				EnterOuterAlt(_localctx, 2);
				{
				State = 166;
				Match(T__18);
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 3);
				{
				State = 167;
				Match(T__19);
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 4);
				{
				State = 168;
				Match(T__20);
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 5);
				{
				State = 169;
				Match(T__21);
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 6);
				{
				State = 170;
				Match(T__22);
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 7);
				{
				State = 171;
				Match(T__23);
				}
				break;
			case T__24:
				EnterOuterAlt(_localctx, 8);
				{
				State = 172;
				Match(T__24);
				}
				break;
			case T__25:
				EnterOuterAlt(_localctx, 9);
				{
				State = 173;
				Match(T__25);
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 10);
				{
				State = 174;
				Match(T__26);
				}
				break;
			case T__27:
				EnterOuterAlt(_localctx, 11);
				{
				State = 175;
				Match(T__27);
				}
				break;
			case T__28:
				EnterOuterAlt(_localctx, 12);
				{
				State = 176;
				Match(T__28);
				}
				break;
			case T__29:
				EnterOuterAlt(_localctx, 13);
				{
				State = 177;
				Match(T__29);
				}
				break;
			case T__30:
				EnterOuterAlt(_localctx, 14);
				{
				State = 178;
				Match(T__30);
				}
				break;
			case T__31:
				EnterOuterAlt(_localctx, 15);
				{
				State = 179;
				Match(T__31);
				}
				break;
			case T__32:
				EnterOuterAlt(_localctx, 16);
				{
				State = 180;
				Match(T__32);
				}
				break;
			case T__33:
				EnterOuterAlt(_localctx, 17);
				{
				State = 181;
				Match(T__33);
				}
				break;
			case T__34:
				EnterOuterAlt(_localctx, 18);
				{
				State = 182;
				Match(T__34);
				}
				break;
			case T__35:
				EnterOuterAlt(_localctx, 19);
				{
				State = 183;
				Match(T__35);
				}
				break;
			case T__36:
				EnterOuterAlt(_localctx, 20);
				{
				State = 184;
				Match(T__36);
				}
				break;
			case T__37:
				EnterOuterAlt(_localctx, 21);
				{
				State = 185;
				Match(T__37);
				}
				break;
			case T__38:
				EnterOuterAlt(_localctx, 22);
				{
				State = 186;
				Match(T__38);
				}
				break;
			case T__39:
				EnterOuterAlt(_localctx, 23);
				{
				State = 187;
				Match(T__39);
				State = 188;
				type_();
				State = 189;
				Match(T__40);
				}
				break;
			case Ident:
				EnterOuterAlt(_localctx, 24);
				{
				State = 191;
				Match(Ident);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Enumval_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IntegerConstant() { return GetToken(FlatBuffersParser.IntegerConstant, 0); }
		public Enumval_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumval_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterEnumval_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitEnumval_decl(this);
		}
	}

	[RuleVersion(0)]
	public Enumval_declContext enumval_decl() {
		Enumval_declContext _localctx = new Enumval_declContext(Context, State);
		EnterRule(_localctx, 22, RULE_enumval_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 194;
			Match(Ident);
			State = 197;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__13) {
				{
				State = 195;
				Match(T__13);
				State = 196;
				Match(IntegerConstant);
				}
			}

			State = 199;
			metadata();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MetadataContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Commasep_metadata_itemContext commasep_metadata_item() {
			return GetRuleContext<Commasep_metadata_itemContext>(0);
		}
		public MetadataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_metadata; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterMetadata(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitMetadata(this);
		}
	}

	[RuleVersion(0)]
	public MetadataContext metadata() {
		MetadataContext _localctx = new MetadataContext(Context, State);
		EnterRule(_localctx, 24, RULE_metadata);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 205;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__15) {
				{
				State = 201;
				Match(T__15);
				State = 202;
				commasep_metadata_item();
				State = 203;
				Match(T__16);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScalarContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BooleanConstant() { return GetToken(FlatBuffersParser.BooleanConstant, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IntegerConstant() { return GetToken(FlatBuffersParser.IntegerConstant, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FloatConstant() { return GetToken(FlatBuffersParser.FloatConstant, 0); }
		public ScalarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scalar; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterScalar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitScalar(this);
		}
	}

	[RuleVersion(0)]
	public ScalarContext scalar() {
		ScalarContext _localctx = new ScalarContext(Context, State);
		EnterRule(_localctx, 26, RULE_scalar);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 207;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 457396837154816L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Commasep_object_itemContext commasep_object_item() {
			return GetRuleContext<Commasep_object_itemContext>(0);
		}
		public ObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterObject(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitObject(this);
		}
	}

	[RuleVersion(0)]
	public ObjectContext @object() {
		ObjectContext _localctx = new ObjectContext(Context, State);
		EnterRule(_localctx, 28, RULE_object);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 209;
			Match(T__7);
			State = 210;
			commasep_object_item();
			State = 211;
			Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Single_valueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ScalarContext scalar() {
			return GetRuleContext<ScalarContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public Single_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_single_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterSingle_value(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitSingle_value(this);
		}
	}

	[RuleVersion(0)]
	public Single_valueContext single_value() {
		Single_valueContext _localctx = new Single_valueContext(Context, State);
		EnterRule(_localctx, 30, RULE_single_value);
		try {
			State = 215;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BooleanConstant:
			case IntegerConstant:
			case FloatConstant:
				EnterOuterAlt(_localctx, 1);
				{
				State = 213;
				scalar();
				}
				break;
			case StringConstant:
				EnterOuterAlt(_localctx, 2);
				{
				State = 214;
				Match(StringConstant);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Single_valueContext single_value() {
			return GetRuleContext<Single_valueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Commasep_valueContext commasep_value() {
			return GetRuleContext<Commasep_valueContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 32, RULE_value);
		try {
			State = 223;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BooleanConstant:
			case IntegerConstant:
			case FloatConstant:
			case StringConstant:
				EnterOuterAlt(_localctx, 1);
				{
				State = 217;
				single_value();
				}
				break;
			case T__7:
				EnterOuterAlt(_localctx, 2);
				{
				State = 218;
				@object();
				}
				break;
			case T__39:
				EnterOuterAlt(_localctx, 3);
				{
				State = 219;
				Match(T__39);
				State = 220;
				commasep_value();
				State = 221;
				Match(T__40);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class File_extension_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public File_extension_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file_extension_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterFile_extension_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitFile_extension_decl(this);
		}
	}

	[RuleVersion(0)]
	public File_extension_declContext file_extension_decl() {
		File_extension_declContext _localctx = new File_extension_declContext(Context, State);
		EnterRule(_localctx, 34, RULE_file_extension_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 225;
			Match(T__41);
			State = 226;
			Match(StringConstant);
			State = 227;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class File_identifier_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public File_identifier_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file_identifier_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterFile_identifier_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitFile_identifier_decl(this);
		}
	}

	[RuleVersion(0)]
	public File_identifier_declContext file_identifier_decl() {
		File_identifier_declContext _localctx = new File_identifier_declContext(Context, State);
		EnterRule(_localctx, 36, RULE_file_identifier_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 229;
			Match(T__42);
			State = 230;
			Match(StringConstant);
			State = 231;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Commasep_enumval_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Enumval_declContext[] enumval_decl() {
			return GetRuleContexts<Enumval_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enumval_declContext enumval_decl(int i) {
			return GetRuleContext<Enumval_declContext>(i);
		}
		public Commasep_enumval_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commasep_enumval_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterCommasep_enumval_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitCommasep_enumval_decl(this);
		}
	}

	[RuleVersion(0)]
	public Commasep_enumval_declContext commasep_enumval_decl() {
		Commasep_enumval_declContext _localctx = new Commasep_enumval_declContext(Context, State);
		EnterRule(_localctx, 38, RULE_commasep_enumval_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 241;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Ident) {
				{
				State = 233;
				enumval_decl();
				State = 238;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__43) {
					{
					{
					State = 234;
					Match(T__43);
					State = 235;
					enumval_decl();
					}
					}
					State = 240;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Commasep_metadata_itemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Ident() { return GetTokens(FlatBuffersParser.Ident); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident(int i) {
			return GetToken(FlatBuffersParser.Ident, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Single_valueContext[] single_value() {
			return GetRuleContexts<Single_valueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Single_valueContext single_value(int i) {
			return GetRuleContext<Single_valueContext>(i);
		}
		public Commasep_metadata_itemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commasep_metadata_item; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterCommasep_metadata_item(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitCommasep_metadata_item(this);
		}
	}

	[RuleVersion(0)]
	public Commasep_metadata_itemContext commasep_metadata_item() {
		Commasep_metadata_itemContext _localctx = new Commasep_metadata_itemContext(Context, State);
		EnterRule(_localctx, 40, RULE_commasep_metadata_item);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 259;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Ident) {
				{
				State = 243;
				Match(Ident);
				State = 246;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__10) {
					{
					State = 244;
					Match(T__10);
					State = 245;
					single_value();
					}
				}

				State = 256;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__43) {
					{
					{
					State = 248;
					Match(T__43);
					State = 249;
					Match(Ident);
					State = 252;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==T__10) {
						{
						State = 250;
						Match(T__10);
						State = 251;
						single_value();
						}
					}

					}
					}
					State = 258;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Commasep_object_itemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Ident() { return GetTokens(FlatBuffersParser.Ident); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident(int i) {
			return GetToken(FlatBuffersParser.Ident, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public Commasep_object_itemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commasep_object_item; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterCommasep_object_item(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitCommasep_object_item(this);
		}
	}

	[RuleVersion(0)]
	public Commasep_object_itemContext commasep_object_item() {
		Commasep_object_itemContext _localctx = new Commasep_object_itemContext(Context, State);
		EnterRule(_localctx, 42, RULE_commasep_object_item);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 273;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Ident) {
				{
				State = 261;
				Match(Ident);
				State = 262;
				Match(T__10);
				State = 263;
				value();
				State = 270;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__43) {
					{
					{
					State = 264;
					Match(T__43);
					State = 265;
					Match(Ident);
					State = 266;
					Match(T__10);
					State = 267;
					value();
					}
					}
					State = 272;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Commasep_valueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public Commasep_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commasep_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterCommasep_value(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitCommasep_value(this);
		}
	}

	[RuleVersion(0)]
	public Commasep_valueContext commasep_value() {
		Commasep_valueContext _localctx = new Commasep_valueContext(Context, State);
		EnterRule(_localctx, 44, RULE_commasep_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 283;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1021446302204160L) != 0)) {
				{
				State = 275;
				value();
				State = 280;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__43) {
					{
					{
					State = 276;
					Match(T__43);
					State = 277;
					value();
					}
					}
					State = 282;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,50,286,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,1,0,1,0,1,0,5,0,50,8,0,10,0,12,0,53,9,0,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,5,0,68,8,0,10,0,12,0,71,9,0,1,0,1,0,1,
		1,1,1,1,1,1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,5,2,86,8,2,10,2,12,2,89,9,2,
		1,2,1,2,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,3,4,101,8,4,1,4,1,4,1,4,1,4,1,
		4,1,4,1,4,4,4,110,8,4,11,4,12,4,111,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,3,
		5,122,8,5,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,7,
		1,7,1,7,1,7,3,7,142,8,7,1,7,1,7,1,7,1,8,1,8,1,8,1,8,4,8,151,8,8,11,8,12,
		8,152,1,8,1,8,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,10,1,10,1,10,1,10,
		1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,
		1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,3,10,193,8,10,1,11,1,11,1,
		11,3,11,198,8,11,1,11,1,11,1,12,1,12,1,12,1,12,3,12,206,8,12,1,13,1,13,
		1,14,1,14,1,14,1,14,1,15,1,15,3,15,216,8,15,1,16,1,16,1,16,1,16,1,16,1,
		16,3,16,224,8,16,1,17,1,17,1,17,1,17,1,18,1,18,1,18,1,18,1,19,1,19,1,19,
		5,19,237,8,19,10,19,12,19,240,9,19,3,19,242,8,19,1,20,1,20,1,20,3,20,247,
		8,20,1,20,1,20,1,20,1,20,3,20,253,8,20,5,20,255,8,20,10,20,12,20,258,9,
		20,3,20,260,8,20,1,21,1,21,1,21,1,21,1,21,1,21,1,21,5,21,269,8,21,10,21,
		12,21,272,9,21,3,21,274,8,21,1,22,1,22,1,22,5,22,279,8,22,10,22,12,22,
		282,9,22,3,22,284,8,22,1,22,0,0,23,0,2,4,6,8,10,12,14,16,18,20,22,24,26,
		28,30,32,34,36,38,40,42,44,0,2,2,0,46,46,49,49,2,0,45,45,47,48,316,0,51,
		1,0,0,0,2,74,1,0,0,0,4,79,1,0,0,0,6,92,1,0,0,0,8,100,1,0,0,0,10,121,1,
		0,0,0,12,128,1,0,0,0,14,132,1,0,0,0,16,146,1,0,0,0,18,156,1,0,0,0,20,192,
		1,0,0,0,22,194,1,0,0,0,24,205,1,0,0,0,26,207,1,0,0,0,28,209,1,0,0,0,30,
		215,1,0,0,0,32,223,1,0,0,0,34,225,1,0,0,0,36,229,1,0,0,0,38,241,1,0,0,
		0,40,259,1,0,0,0,42,273,1,0,0,0,44,283,1,0,0,0,46,47,3,2,1,0,47,48,6,0,
		-1,0,48,50,1,0,0,0,49,46,1,0,0,0,50,53,1,0,0,0,51,49,1,0,0,0,51,52,1,0,
		0,0,52,69,1,0,0,0,53,51,1,0,0,0,54,55,3,4,2,0,55,56,6,0,-1,0,56,68,1,0,
		0,0,57,58,3,8,4,0,58,59,6,0,-1,0,59,68,1,0,0,0,60,68,3,10,5,0,61,68,3,
		12,6,0,62,68,3,34,17,0,63,68,3,36,18,0,64,68,3,6,3,0,65,68,3,16,8,0,66,
		68,3,28,14,0,67,54,1,0,0,0,67,57,1,0,0,0,67,60,1,0,0,0,67,61,1,0,0,0,67,
		62,1,0,0,0,67,63,1,0,0,0,67,64,1,0,0,0,67,65,1,0,0,0,67,66,1,0,0,0,68,
		71,1,0,0,0,69,67,1,0,0,0,69,70,1,0,0,0,70,72,1,0,0,0,71,69,1,0,0,0,72,
		73,5,0,0,1,73,1,1,0,0,0,74,75,5,1,0,0,75,76,5,49,0,0,76,77,6,1,-1,0,77,
		78,5,2,0,0,78,3,1,0,0,0,79,80,5,3,0,0,80,81,5,46,0,0,81,87,6,2,-1,0,82,
		83,5,4,0,0,83,84,5,46,0,0,84,86,6,2,-1,0,85,82,1,0,0,0,86,89,1,0,0,0,87,
		85,1,0,0,0,87,88,1,0,0,0,88,90,1,0,0,0,89,87,1,0,0,0,90,91,5,2,0,0,91,
		5,1,0,0,0,92,93,5,5,0,0,93,94,7,0,0,0,94,95,5,2,0,0,95,7,1,0,0,0,96,97,
		5,6,0,0,97,101,6,4,-1,0,98,99,5,7,0,0,99,101,6,4,-1,0,100,96,1,0,0,0,100,
		98,1,0,0,0,101,102,1,0,0,0,102,103,5,46,0,0,103,104,6,4,-1,0,104,105,3,
		24,12,0,105,109,5,8,0,0,106,107,3,14,7,0,107,108,6,4,-1,0,108,110,1,0,
		0,0,109,106,1,0,0,0,110,111,1,0,0,0,111,109,1,0,0,0,111,112,1,0,0,0,112,
		113,1,0,0,0,113,114,5,9,0,0,114,9,1,0,0,0,115,116,5,10,0,0,116,117,5,46,
		0,0,117,118,5,11,0,0,118,122,3,20,10,0,119,120,5,12,0,0,120,122,5,46,0,
		0,121,115,1,0,0,0,121,119,1,0,0,0,122,123,1,0,0,0,123,124,3,24,12,0,124,
		125,5,8,0,0,125,126,3,38,19,0,126,127,5,9,0,0,127,11,1,0,0,0,128,129,5,
		13,0,0,129,130,5,46,0,0,130,131,5,2,0,0,131,13,1,0,0,0,132,133,5,46,0,
		0,133,134,6,7,-1,0,134,135,5,11,0,0,135,136,3,20,10,0,136,141,6,7,-1,0,
		137,138,5,14,0,0,138,139,3,26,13,0,139,140,6,7,-1,0,140,142,1,0,0,0,141,
		137,1,0,0,0,141,142,1,0,0,0,142,143,1,0,0,0,143,144,3,24,12,0,144,145,
		5,2,0,0,145,15,1,0,0,0,146,147,5,15,0,0,147,148,5,46,0,0,148,150,5,8,0,
		0,149,151,3,18,9,0,150,149,1,0,0,0,151,152,1,0,0,0,152,150,1,0,0,0,152,
		153,1,0,0,0,153,154,1,0,0,0,154,155,5,9,0,0,155,17,1,0,0,0,156,157,5,46,
		0,0,157,158,5,16,0,0,158,159,5,46,0,0,159,160,5,17,0,0,160,161,5,11,0,
		0,161,162,5,46,0,0,162,163,3,24,12,0,163,164,5,2,0,0,164,19,1,0,0,0,165,
		193,5,18,0,0,166,193,5,19,0,0,167,193,5,20,0,0,168,193,5,21,0,0,169,193,
		5,22,0,0,170,193,5,23,0,0,171,193,5,24,0,0,172,193,5,25,0,0,173,193,5,
		26,0,0,174,193,5,27,0,0,175,193,5,28,0,0,176,193,5,29,0,0,177,193,5,30,
		0,0,178,193,5,31,0,0,179,193,5,32,0,0,180,193,5,33,0,0,181,193,5,34,0,
		0,182,193,5,35,0,0,183,193,5,36,0,0,184,193,5,37,0,0,185,193,5,38,0,0,
		186,193,5,39,0,0,187,188,5,40,0,0,188,189,3,20,10,0,189,190,5,41,0,0,190,
		193,1,0,0,0,191,193,5,46,0,0,192,165,1,0,0,0,192,166,1,0,0,0,192,167,1,
		0,0,0,192,168,1,0,0,0,192,169,1,0,0,0,192,170,1,0,0,0,192,171,1,0,0,0,
		192,172,1,0,0,0,192,173,1,0,0,0,192,174,1,0,0,0,192,175,1,0,0,0,192,176,
		1,0,0,0,192,177,1,0,0,0,192,178,1,0,0,0,192,179,1,0,0,0,192,180,1,0,0,
		0,192,181,1,0,0,0,192,182,1,0,0,0,192,183,1,0,0,0,192,184,1,0,0,0,192,
		185,1,0,0,0,192,186,1,0,0,0,192,187,1,0,0,0,192,191,1,0,0,0,193,21,1,0,
		0,0,194,197,5,46,0,0,195,196,5,14,0,0,196,198,5,47,0,0,197,195,1,0,0,0,
		197,198,1,0,0,0,198,199,1,0,0,0,199,200,3,24,12,0,200,23,1,0,0,0,201,202,
		5,16,0,0,202,203,3,40,20,0,203,204,5,17,0,0,204,206,1,0,0,0,205,201,1,
		0,0,0,205,206,1,0,0,0,206,25,1,0,0,0,207,208,7,1,0,0,208,27,1,0,0,0,209,
		210,5,8,0,0,210,211,3,42,21,0,211,212,5,9,0,0,212,29,1,0,0,0,213,216,3,
		26,13,0,214,216,5,49,0,0,215,213,1,0,0,0,215,214,1,0,0,0,216,31,1,0,0,
		0,217,224,3,30,15,0,218,224,3,28,14,0,219,220,5,40,0,0,220,221,3,44,22,
		0,221,222,5,41,0,0,222,224,1,0,0,0,223,217,1,0,0,0,223,218,1,0,0,0,223,
		219,1,0,0,0,224,33,1,0,0,0,225,226,5,42,0,0,226,227,5,49,0,0,227,228,5,
		2,0,0,228,35,1,0,0,0,229,230,5,43,0,0,230,231,5,49,0,0,231,232,5,2,0,0,
		232,37,1,0,0,0,233,238,3,22,11,0,234,235,5,44,0,0,235,237,3,22,11,0,236,
		234,1,0,0,0,237,240,1,0,0,0,238,236,1,0,0,0,238,239,1,0,0,0,239,242,1,
		0,0,0,240,238,1,0,0,0,241,233,1,0,0,0,241,242,1,0,0,0,242,39,1,0,0,0,243,
		246,5,46,0,0,244,245,5,11,0,0,245,247,3,30,15,0,246,244,1,0,0,0,246,247,
		1,0,0,0,247,256,1,0,0,0,248,249,5,44,0,0,249,252,5,46,0,0,250,251,5,11,
		0,0,251,253,3,30,15,0,252,250,1,0,0,0,252,253,1,0,0,0,253,255,1,0,0,0,
		254,248,1,0,0,0,255,258,1,0,0,0,256,254,1,0,0,0,256,257,1,0,0,0,257,260,
		1,0,0,0,258,256,1,0,0,0,259,243,1,0,0,0,259,260,1,0,0,0,260,41,1,0,0,0,
		261,262,5,46,0,0,262,263,5,11,0,0,263,270,3,32,16,0,264,265,5,44,0,0,265,
		266,5,46,0,0,266,267,5,11,0,0,267,269,3,32,16,0,268,264,1,0,0,0,269,272,
		1,0,0,0,270,268,1,0,0,0,270,271,1,0,0,0,271,274,1,0,0,0,272,270,1,0,0,
		0,273,261,1,0,0,0,273,274,1,0,0,0,274,43,1,0,0,0,275,280,3,32,16,0,276,
		277,5,44,0,0,277,279,3,32,16,0,278,276,1,0,0,0,279,282,1,0,0,0,280,278,
		1,0,0,0,280,281,1,0,0,0,281,284,1,0,0,0,282,280,1,0,0,0,283,275,1,0,0,
		0,283,284,1,0,0,0,284,45,1,0,0,0,24,51,67,69,87,100,111,121,141,152,192,
		197,205,215,223,238,241,246,252,256,259,270,273,280,283
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
