//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./FlatBuffers.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class FlatBuffersParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, T__26=27, T__27=28, T__28=29, T__29=30, T__30=31, 
		T__31=32, T__32=33, T__33=34, T__34=35, T__35=36, T__36=37, T__37=38, 
		T__38=39, T__39=40, T__40=41, T__41=42, T__42=43, T__43=44, BooleanConstant=45, 
		Ident=46, IntegerConstant=47, FloatConstant=48, StringConstant=49, WS=50;
	public const int
		RULE_schema = 0, RULE_include = 1, RULE_namespace_decl = 2, RULE_attribute_decl = 3, 
		RULE_type_decl = 4, RULE_enum_decl = 5, RULE_root_decl = 6, RULE_field_decl = 7, 
		RULE_rpc_decl = 8, RULE_rpc_method = 9, RULE_type_ = 10, RULE_enumval_decl = 11, 
		RULE_metadata = 12, RULE_scalar = 13, RULE_object = 14, RULE_single_value = 15, 
		RULE_value = 16, RULE_file_extension_decl = 17, RULE_file_identifier_decl = 18, 
		RULE_commasep_enumval_decl = 19, RULE_commasep_metadata_item = 20, RULE_commasep_object_item = 21, 
		RULE_commasep_value = 22;
	public static readonly string[] ruleNames = {
		"schema", "include", "namespace_decl", "attribute_decl", "type_decl", 
		"enum_decl", "root_decl", "field_decl", "rpc_decl", "rpc_method", "type_", 
		"enumval_decl", "metadata", "scalar", "object", "single_value", "value", 
		"file_extension_decl", "file_identifier_decl", "commasep_enumval_decl", 
		"commasep_metadata_item", "commasep_object_item", "commasep_value"
	};

	private static readonly string[] _LiteralNames = {
		null, "'include'", "';'", "'namespace'", "'.'", "'attribute'", "'table'", 
		"'struct'", "'{'", "'}'", "'enum'", "':'", "'union'", "'root_type'", "'='", 
		"'rpc_service'", "'('", "')'", "'bool'", "'byte'", "'ubyte'", "'short'", 
		"'ushort'", "'int'", "'uint'", "'float'", "'long'", "'ulong'", "'double'", 
		"'int8'", "'uint8'", "'int16'", "'uint16'", "'int32'", "'uint32'", "'int64'", 
		"'uint64'", "'float32'", "'float64'", "'string'", "'['", "']'", "'file_extension'", 
		"'file_identifier'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, "BooleanConstant", 
		"Ident", "IntegerConstant", "FloatConstant", "StringConstant", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "FlatBuffers.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static FlatBuffersParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public FlatBuffersParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public FlatBuffersParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class SchemaContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(FlatBuffersParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public IncludeContext[] include() {
			return GetRuleContexts<IncludeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public IncludeContext include(int i) {
			return GetRuleContext<IncludeContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Namespace_declContext[] namespace_decl() {
			return GetRuleContexts<Namespace_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Namespace_declContext namespace_decl(int i) {
			return GetRuleContext<Namespace_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_declContext[] type_decl() {
			return GetRuleContexts<Type_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Type_declContext type_decl(int i) {
			return GetRuleContext<Type_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enum_declContext[] enum_decl() {
			return GetRuleContexts<Enum_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enum_declContext enum_decl(int i) {
			return GetRuleContext<Enum_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Root_declContext[] root_decl() {
			return GetRuleContexts<Root_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Root_declContext root_decl(int i) {
			return GetRuleContext<Root_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public File_extension_declContext[] file_extension_decl() {
			return GetRuleContexts<File_extension_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public File_extension_declContext file_extension_decl(int i) {
			return GetRuleContext<File_extension_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public File_identifier_declContext[] file_identifier_decl() {
			return GetRuleContexts<File_identifier_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public File_identifier_declContext file_identifier_decl(int i) {
			return GetRuleContext<File_identifier_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Attribute_declContext[] attribute_decl() {
			return GetRuleContexts<Attribute_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Attribute_declContext attribute_decl(int i) {
			return GetRuleContext<Attribute_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Rpc_declContext[] rpc_decl() {
			return GetRuleContexts<Rpc_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Rpc_declContext rpc_decl(int i) {
			return GetRuleContext<Rpc_declContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext[] @object() {
			return GetRuleContexts<ObjectContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object(int i) {
			return GetRuleContext<ObjectContext>(i);
		}
		public SchemaContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_schema; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterSchema(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitSchema(this);
		}
	}

	[RuleVersion(0)]
	public SchemaContext schema() {
		SchemaContext _localctx = new SchemaContext(Context, State);
		EnterRule(_localctx, 0, RULE_schema);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 49;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__0) {
				{
				{
				State = 46;
				include();
				}
				}
				State = 51;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 63;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 13194139579880L) != 0)) {
				{
				State = 61;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case T__2:
					{
					State = 52;
					namespace_decl();
					}
					break;
				case T__5:
				case T__6:
					{
					State = 53;
					type_decl();
					}
					break;
				case T__9:
				case T__11:
					{
					State = 54;
					enum_decl();
					}
					break;
				case T__12:
					{
					State = 55;
					root_decl();
					}
					break;
				case T__41:
					{
					State = 56;
					file_extension_decl();
					}
					break;
				case T__42:
					{
					State = 57;
					file_identifier_decl();
					}
					break;
				case T__4:
					{
					State = 58;
					attribute_decl();
					}
					break;
				case T__14:
					{
					State = 59;
					rpc_decl();
					}
					break;
				case T__7:
					{
					State = 60;
					@object();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 65;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 66;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IncludeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public IncludeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_include; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterInclude(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitInclude(this);
		}
	}

	[RuleVersion(0)]
	public IncludeContext include() {
		IncludeContext _localctx = new IncludeContext(Context, State);
		EnterRule(_localctx, 2, RULE_include);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 68;
			Match(T__0);
			State = 69;
			Match(StringConstant);
			State = 70;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Namespace_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Ident() { return GetTokens(FlatBuffersParser.Ident); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident(int i) {
			return GetToken(FlatBuffersParser.Ident, i);
		}
		public Namespace_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespace_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterNamespace_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitNamespace_decl(this);
		}
	}

	[RuleVersion(0)]
	public Namespace_declContext namespace_decl() {
		Namespace_declContext _localctx = new Namespace_declContext(Context, State);
		EnterRule(_localctx, 4, RULE_namespace_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 72;
			Match(T__2);
			State = 73;
			Match(Ident);
			State = 78;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==T__3) {
				{
				{
				State = 74;
				Match(T__3);
				State = 75;
				Match(Ident);
				}
				}
				State = 80;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 81;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Attribute_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public Attribute_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_attribute_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterAttribute_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitAttribute_decl(this);
		}
	}

	[RuleVersion(0)]
	public Attribute_declContext attribute_decl() {
		Attribute_declContext _localctx = new Attribute_declContext(Context, State);
		EnterRule(_localctx, 6, RULE_attribute_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83;
			Match(T__4);
			State = 84;
			_la = TokenStream.LA(1);
			if ( !(_la==Ident || _la==StringConstant) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 85;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Field_declContext[] field_decl() {
			return GetRuleContexts<Field_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Field_declContext field_decl(int i) {
			return GetRuleContext<Field_declContext>(i);
		}
		public Type_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterType_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitType_decl(this);
		}
	}

	[RuleVersion(0)]
	public Type_declContext type_decl() {
		Type_declContext _localctx = new Type_declContext(Context, State);
		EnterRule(_localctx, 8, RULE_type_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			_la = TokenStream.LA(1);
			if ( !(_la==T__5 || _la==T__6) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			State = 88;
			Match(Ident);
			State = 89;
			metadata();
			State = 90;
			Match(T__7);
			State = 92;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 91;
				field_decl();
				}
				}
				State = 94;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Ident );
			State = 96;
			Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Enum_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Commasep_enumval_declContext commasep_enumval_decl() {
			return GetRuleContext<Commasep_enumval_declContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		public Enum_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enum_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterEnum_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitEnum_decl(this);
		}
	}

	[RuleVersion(0)]
	public Enum_declContext enum_decl() {
		Enum_declContext _localctx = new Enum_declContext(Context, State);
		EnterRule(_localctx, 10, RULE_enum_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__9:
				{
				State = 98;
				Match(T__9);
				State = 99;
				Match(Ident);
				State = 100;
				Match(T__10);
				State = 101;
				type_();
				}
				break;
			case T__11:
				{
				State = 102;
				Match(T__11);
				State = 103;
				Match(Ident);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 106;
			metadata();
			State = 107;
			Match(T__7);
			State = 108;
			commasep_enumval_decl();
			State = 109;
			Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Root_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		public Root_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_root_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterRoot_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitRoot_decl(this);
		}
	}

	[RuleVersion(0)]
	public Root_declContext root_decl() {
		Root_declContext _localctx = new Root_declContext(Context, State);
		EnterRule(_localctx, 12, RULE_root_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 111;
			Match(T__12);
			State = 112;
			Match(Ident);
			State = 113;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Field_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ScalarContext scalar() {
			return GetRuleContext<ScalarContext>(0);
		}
		public Field_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_field_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterField_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitField_decl(this);
		}
	}

	[RuleVersion(0)]
	public Field_declContext field_decl() {
		Field_declContext _localctx = new Field_declContext(Context, State);
		EnterRule(_localctx, 14, RULE_field_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 115;
			Match(Ident);
			State = 116;
			Match(T__10);
			State = 117;
			type_();
			State = 120;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__13) {
				{
				State = 118;
				Match(T__13);
				State = 119;
				scalar();
				}
			}

			State = 122;
			metadata();
			State = 123;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rpc_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Rpc_methodContext[] rpc_method() {
			return GetRuleContexts<Rpc_methodContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Rpc_methodContext rpc_method(int i) {
			return GetRuleContext<Rpc_methodContext>(i);
		}
		public Rpc_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rpc_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterRpc_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitRpc_decl(this);
		}
	}

	[RuleVersion(0)]
	public Rpc_declContext rpc_decl() {
		Rpc_declContext _localctx = new Rpc_declContext(Context, State);
		EnterRule(_localctx, 16, RULE_rpc_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 125;
			Match(T__14);
			State = 126;
			Match(Ident);
			State = 127;
			Match(T__7);
			State = 129;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 128;
				rpc_method();
				}
				}
				State = 131;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==Ident );
			State = 133;
			Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Rpc_methodContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Ident() { return GetTokens(FlatBuffersParser.Ident); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident(int i) {
			return GetToken(FlatBuffersParser.Ident, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		public Rpc_methodContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_rpc_method; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterRpc_method(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitRpc_method(this);
		}
	}

	[RuleVersion(0)]
	public Rpc_methodContext rpc_method() {
		Rpc_methodContext _localctx = new Rpc_methodContext(Context, State);
		EnterRule(_localctx, 18, RULE_rpc_method);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 135;
			Match(Ident);
			State = 136;
			Match(T__15);
			State = 137;
			Match(Ident);
			State = 138;
			Match(T__16);
			State = 139;
			Match(T__10);
			State = 140;
			Match(Ident);
			State = 141;
			metadata();
			State = 142;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Type_Context : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Type_Context type_() {
			return GetRuleContext<Type_Context>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		public Type_Context(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type_; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterType_(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitType_(this);
		}
	}

	[RuleVersion(0)]
	public Type_Context type_() {
		Type_Context _localctx = new Type_Context(Context, State);
		EnterRule(_localctx, 20, RULE_type_);
		try {
			State = 171;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__17:
				EnterOuterAlt(_localctx, 1);
				{
				State = 144;
				Match(T__17);
				}
				break;
			case T__18:
				EnterOuterAlt(_localctx, 2);
				{
				State = 145;
				Match(T__18);
				}
				break;
			case T__19:
				EnterOuterAlt(_localctx, 3);
				{
				State = 146;
				Match(T__19);
				}
				break;
			case T__20:
				EnterOuterAlt(_localctx, 4);
				{
				State = 147;
				Match(T__20);
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 5);
				{
				State = 148;
				Match(T__21);
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 6);
				{
				State = 149;
				Match(T__22);
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 7);
				{
				State = 150;
				Match(T__23);
				}
				break;
			case T__24:
				EnterOuterAlt(_localctx, 8);
				{
				State = 151;
				Match(T__24);
				}
				break;
			case T__25:
				EnterOuterAlt(_localctx, 9);
				{
				State = 152;
				Match(T__25);
				}
				break;
			case T__26:
				EnterOuterAlt(_localctx, 10);
				{
				State = 153;
				Match(T__26);
				}
				break;
			case T__27:
				EnterOuterAlt(_localctx, 11);
				{
				State = 154;
				Match(T__27);
				}
				break;
			case T__28:
				EnterOuterAlt(_localctx, 12);
				{
				State = 155;
				Match(T__28);
				}
				break;
			case T__29:
				EnterOuterAlt(_localctx, 13);
				{
				State = 156;
				Match(T__29);
				}
				break;
			case T__30:
				EnterOuterAlt(_localctx, 14);
				{
				State = 157;
				Match(T__30);
				}
				break;
			case T__31:
				EnterOuterAlt(_localctx, 15);
				{
				State = 158;
				Match(T__31);
				}
				break;
			case T__32:
				EnterOuterAlt(_localctx, 16);
				{
				State = 159;
				Match(T__32);
				}
				break;
			case T__33:
				EnterOuterAlt(_localctx, 17);
				{
				State = 160;
				Match(T__33);
				}
				break;
			case T__34:
				EnterOuterAlt(_localctx, 18);
				{
				State = 161;
				Match(T__34);
				}
				break;
			case T__35:
				EnterOuterAlt(_localctx, 19);
				{
				State = 162;
				Match(T__35);
				}
				break;
			case T__36:
				EnterOuterAlt(_localctx, 20);
				{
				State = 163;
				Match(T__36);
				}
				break;
			case T__37:
				EnterOuterAlt(_localctx, 21);
				{
				State = 164;
				Match(T__37);
				}
				break;
			case T__38:
				EnterOuterAlt(_localctx, 22);
				{
				State = 165;
				Match(T__38);
				}
				break;
			case T__39:
				EnterOuterAlt(_localctx, 23);
				{
				State = 166;
				Match(T__39);
				State = 167;
				type_();
				State = 168;
				Match(T__40);
				}
				break;
			case Ident:
				EnterOuterAlt(_localctx, 24);
				{
				State = 170;
				Match(Ident);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Enumval_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident() { return GetToken(FlatBuffersParser.Ident, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MetadataContext metadata() {
			return GetRuleContext<MetadataContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IntegerConstant() { return GetToken(FlatBuffersParser.IntegerConstant, 0); }
		public Enumval_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumval_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterEnumval_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitEnumval_decl(this);
		}
	}

	[RuleVersion(0)]
	public Enumval_declContext enumval_decl() {
		Enumval_declContext _localctx = new Enumval_declContext(Context, State);
		EnterRule(_localctx, 22, RULE_enumval_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 173;
			Match(Ident);
			State = 176;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__13) {
				{
				State = 174;
				Match(T__13);
				State = 175;
				Match(IntegerConstant);
				}
			}

			State = 178;
			metadata();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MetadataContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Commasep_metadata_itemContext commasep_metadata_item() {
			return GetRuleContext<Commasep_metadata_itemContext>(0);
		}
		public MetadataContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_metadata; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterMetadata(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitMetadata(this);
		}
	}

	[RuleVersion(0)]
	public MetadataContext metadata() {
		MetadataContext _localctx = new MetadataContext(Context, State);
		EnterRule(_localctx, 24, RULE_metadata);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==T__15) {
				{
				State = 180;
				Match(T__15);
				State = 181;
				commasep_metadata_item();
				State = 182;
				Match(T__16);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ScalarContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BooleanConstant() { return GetToken(FlatBuffersParser.BooleanConstant, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IntegerConstant() { return GetToken(FlatBuffersParser.IntegerConstant, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FloatConstant() { return GetToken(FlatBuffersParser.FloatConstant, 0); }
		public ScalarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scalar; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterScalar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitScalar(this);
		}
	}

	[RuleVersion(0)]
	public ScalarContext scalar() {
		ScalarContext _localctx = new ScalarContext(Context, State);
		EnterRule(_localctx, 26, RULE_scalar);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 457396837154816L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjectContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Commasep_object_itemContext commasep_object_item() {
			return GetRuleContext<Commasep_object_itemContext>(0);
		}
		public ObjectContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_object; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterObject(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitObject(this);
		}
	}

	[RuleVersion(0)]
	public ObjectContext @object() {
		ObjectContext _localctx = new ObjectContext(Context, State);
		EnterRule(_localctx, 28, RULE_object);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			Match(T__7);
			State = 189;
			commasep_object_item();
			State = 190;
			Match(T__8);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Single_valueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ScalarContext scalar() {
			return GetRuleContext<ScalarContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public Single_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_single_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterSingle_value(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitSingle_value(this);
		}
	}

	[RuleVersion(0)]
	public Single_valueContext single_value() {
		Single_valueContext _localctx = new Single_valueContext(Context, State);
		EnterRule(_localctx, 30, RULE_single_value);
		try {
			State = 194;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BooleanConstant:
			case IntegerConstant:
			case FloatConstant:
				EnterOuterAlt(_localctx, 1);
				{
				State = 192;
				scalar();
				}
				break;
			case StringConstant:
				EnterOuterAlt(_localctx, 2);
				{
				State = 193;
				Match(StringConstant);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ValueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Single_valueContext single_value() {
			return GetRuleContext<Single_valueContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ObjectContext @object() {
			return GetRuleContext<ObjectContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Commasep_valueContext commasep_value() {
			return GetRuleContext<Commasep_valueContext>(0);
		}
		public ValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterValue(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitValue(this);
		}
	}

	[RuleVersion(0)]
	public ValueContext value() {
		ValueContext _localctx = new ValueContext(Context, State);
		EnterRule(_localctx, 32, RULE_value);
		try {
			State = 202;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BooleanConstant:
			case IntegerConstant:
			case FloatConstant:
			case StringConstant:
				EnterOuterAlt(_localctx, 1);
				{
				State = 196;
				single_value();
				}
				break;
			case T__7:
				EnterOuterAlt(_localctx, 2);
				{
				State = 197;
				@object();
				}
				break;
			case T__39:
				EnterOuterAlt(_localctx, 3);
				{
				State = 198;
				Match(T__39);
				State = 199;
				commasep_value();
				State = 200;
				Match(T__40);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class File_extension_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public File_extension_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file_extension_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterFile_extension_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitFile_extension_decl(this);
		}
	}

	[RuleVersion(0)]
	public File_extension_declContext file_extension_decl() {
		File_extension_declContext _localctx = new File_extension_declContext(Context, State);
		EnterRule(_localctx, 34, RULE_file_extension_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 204;
			Match(T__41);
			State = 205;
			Match(StringConstant);
			State = 206;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class File_identifier_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode StringConstant() { return GetToken(FlatBuffersParser.StringConstant, 0); }
		public File_identifier_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file_identifier_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterFile_identifier_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitFile_identifier_decl(this);
		}
	}

	[RuleVersion(0)]
	public File_identifier_declContext file_identifier_decl() {
		File_identifier_declContext _localctx = new File_identifier_declContext(Context, State);
		EnterRule(_localctx, 36, RULE_file_identifier_decl);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 208;
			Match(T__42);
			State = 209;
			Match(StringConstant);
			State = 210;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Commasep_enumval_declContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Enumval_declContext[] enumval_decl() {
			return GetRuleContexts<Enumval_declContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Enumval_declContext enumval_decl(int i) {
			return GetRuleContext<Enumval_declContext>(i);
		}
		public Commasep_enumval_declContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commasep_enumval_decl; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterCommasep_enumval_decl(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitCommasep_enumval_decl(this);
		}
	}

	[RuleVersion(0)]
	public Commasep_enumval_declContext commasep_enumval_decl() {
		Commasep_enumval_declContext _localctx = new Commasep_enumval_declContext(Context, State);
		EnterRule(_localctx, 38, RULE_commasep_enumval_decl);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 220;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Ident) {
				{
				State = 212;
				enumval_decl();
				State = 217;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__43) {
					{
					{
					State = 213;
					Match(T__43);
					State = 214;
					enumval_decl();
					}
					}
					State = 219;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Commasep_metadata_itemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Ident() { return GetTokens(FlatBuffersParser.Ident); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident(int i) {
			return GetToken(FlatBuffersParser.Ident, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public Single_valueContext[] single_value() {
			return GetRuleContexts<Single_valueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Single_valueContext single_value(int i) {
			return GetRuleContext<Single_valueContext>(i);
		}
		public Commasep_metadata_itemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commasep_metadata_item; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterCommasep_metadata_item(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitCommasep_metadata_item(this);
		}
	}

	[RuleVersion(0)]
	public Commasep_metadata_itemContext commasep_metadata_item() {
		Commasep_metadata_itemContext _localctx = new Commasep_metadata_itemContext(Context, State);
		EnterRule(_localctx, 40, RULE_commasep_metadata_item);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 238;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Ident) {
				{
				State = 222;
				Match(Ident);
				State = 225;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==T__10) {
					{
					State = 223;
					Match(T__10);
					State = 224;
					single_value();
					}
				}

				State = 235;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__43) {
					{
					{
					State = 227;
					Match(T__43);
					State = 228;
					Match(Ident);
					State = 231;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					if (_la==T__10) {
						{
						State = 229;
						Match(T__10);
						State = 230;
						single_value();
						}
					}

					}
					}
					State = 237;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Commasep_object_itemContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Ident() { return GetTokens(FlatBuffersParser.Ident); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Ident(int i) {
			return GetToken(FlatBuffersParser.Ident, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public Commasep_object_itemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commasep_object_item; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterCommasep_object_item(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitCommasep_object_item(this);
		}
	}

	[RuleVersion(0)]
	public Commasep_object_itemContext commasep_object_item() {
		Commasep_object_itemContext _localctx = new Commasep_object_itemContext(Context, State);
		EnterRule(_localctx, 42, RULE_commasep_object_item);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 252;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==Ident) {
				{
				State = 240;
				Match(Ident);
				State = 241;
				Match(T__10);
				State = 242;
				value();
				State = 249;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__43) {
					{
					{
					State = 243;
					Match(T__43);
					State = 244;
					Match(Ident);
					State = 245;
					Match(T__10);
					State = 246;
					value();
					}
					}
					State = 251;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Commasep_valueContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext[] value() {
			return GetRuleContexts<ValueContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ValueContext value(int i) {
			return GetRuleContext<ValueContext>(i);
		}
		public Commasep_valueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commasep_value; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.EnterCommasep_value(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			IFlatBuffersListener typedListener = listener as IFlatBuffersListener;
			if (typedListener != null) typedListener.ExitCommasep_value(this);
		}
	}

	[RuleVersion(0)]
	public Commasep_valueContext commasep_value() {
		Commasep_valueContext _localctx = new Commasep_valueContext(Context, State);
		EnterRule(_localctx, 44, RULE_commasep_value);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 262;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1021446302204160L) != 0)) {
				{
				State = 254;
				value();
				State = 259;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==T__43) {
					{
					{
					State = 255;
					Match(T__43);
					State = 256;
					value();
					}
					}
					State = 261;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,50,265,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,7,14,
		2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,7,21,
		2,22,7,22,1,0,5,0,48,8,0,10,0,12,0,51,9,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,5,0,62,8,0,10,0,12,0,65,9,0,1,0,1,0,1,1,1,1,1,1,1,1,1,2,1,2,1,
		2,1,2,5,2,77,8,2,10,2,12,2,80,9,2,1,2,1,2,1,3,1,3,1,3,1,3,1,4,1,4,1,4,
		1,4,1,4,4,4,93,8,4,11,4,12,4,94,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,3,5,105,
		8,5,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,3,7,121,8,
		7,1,7,1,7,1,7,1,8,1,8,1,8,1,8,4,8,130,8,8,11,8,12,8,131,1,8,1,8,1,9,1,
		9,1,9,1,9,1,9,1,9,1,9,1,9,1,9,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,
		1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,1,10,
		1,10,1,10,1,10,1,10,1,10,3,10,172,8,10,1,11,1,11,1,11,3,11,177,8,11,1,
		11,1,11,1,12,1,12,1,12,1,12,3,12,185,8,12,1,13,1,13,1,14,1,14,1,14,1,14,
		1,15,1,15,3,15,195,8,15,1,16,1,16,1,16,1,16,1,16,1,16,3,16,203,8,16,1,
		17,1,17,1,17,1,17,1,18,1,18,1,18,1,18,1,19,1,19,1,19,5,19,216,8,19,10,
		19,12,19,219,9,19,3,19,221,8,19,1,20,1,20,1,20,3,20,226,8,20,1,20,1,20,
		1,20,1,20,3,20,232,8,20,5,20,234,8,20,10,20,12,20,237,9,20,3,20,239,8,
		20,1,21,1,21,1,21,1,21,1,21,1,21,1,21,5,21,248,8,21,10,21,12,21,251,9,
		21,3,21,253,8,21,1,22,1,22,1,22,5,22,258,8,22,10,22,12,22,261,9,22,3,22,
		263,8,22,1,22,0,0,23,0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30,32,34,
		36,38,40,42,44,0,3,2,0,46,46,49,49,1,0,6,7,2,0,45,45,47,48,294,0,49,1,
		0,0,0,2,68,1,0,0,0,4,72,1,0,0,0,6,83,1,0,0,0,8,87,1,0,0,0,10,104,1,0,0,
		0,12,111,1,0,0,0,14,115,1,0,0,0,16,125,1,0,0,0,18,135,1,0,0,0,20,171,1,
		0,0,0,22,173,1,0,0,0,24,184,1,0,0,0,26,186,1,0,0,0,28,188,1,0,0,0,30,194,
		1,0,0,0,32,202,1,0,0,0,34,204,1,0,0,0,36,208,1,0,0,0,38,220,1,0,0,0,40,
		238,1,0,0,0,42,252,1,0,0,0,44,262,1,0,0,0,46,48,3,2,1,0,47,46,1,0,0,0,
		48,51,1,0,0,0,49,47,1,0,0,0,49,50,1,0,0,0,50,63,1,0,0,0,51,49,1,0,0,0,
		52,62,3,4,2,0,53,62,3,8,4,0,54,62,3,10,5,0,55,62,3,12,6,0,56,62,3,34,17,
		0,57,62,3,36,18,0,58,62,3,6,3,0,59,62,3,16,8,0,60,62,3,28,14,0,61,52,1,
		0,0,0,61,53,1,0,0,0,61,54,1,0,0,0,61,55,1,0,0,0,61,56,1,0,0,0,61,57,1,
		0,0,0,61,58,1,0,0,0,61,59,1,0,0,0,61,60,1,0,0,0,62,65,1,0,0,0,63,61,1,
		0,0,0,63,64,1,0,0,0,64,66,1,0,0,0,65,63,1,0,0,0,66,67,5,0,0,1,67,1,1,0,
		0,0,68,69,5,1,0,0,69,70,5,49,0,0,70,71,5,2,0,0,71,3,1,0,0,0,72,73,5,3,
		0,0,73,78,5,46,0,0,74,75,5,4,0,0,75,77,5,46,0,0,76,74,1,0,0,0,77,80,1,
		0,0,0,78,76,1,0,0,0,78,79,1,0,0,0,79,81,1,0,0,0,80,78,1,0,0,0,81,82,5,
		2,0,0,82,5,1,0,0,0,83,84,5,5,0,0,84,85,7,0,0,0,85,86,5,2,0,0,86,7,1,0,
		0,0,87,88,7,1,0,0,88,89,5,46,0,0,89,90,3,24,12,0,90,92,5,8,0,0,91,93,3,
		14,7,0,92,91,1,0,0,0,93,94,1,0,0,0,94,92,1,0,0,0,94,95,1,0,0,0,95,96,1,
		0,0,0,96,97,5,9,0,0,97,9,1,0,0,0,98,99,5,10,0,0,99,100,5,46,0,0,100,101,
		5,11,0,0,101,105,3,20,10,0,102,103,5,12,0,0,103,105,5,46,0,0,104,98,1,
		0,0,0,104,102,1,0,0,0,105,106,1,0,0,0,106,107,3,24,12,0,107,108,5,8,0,
		0,108,109,3,38,19,0,109,110,5,9,0,0,110,11,1,0,0,0,111,112,5,13,0,0,112,
		113,5,46,0,0,113,114,5,2,0,0,114,13,1,0,0,0,115,116,5,46,0,0,116,117,5,
		11,0,0,117,120,3,20,10,0,118,119,5,14,0,0,119,121,3,26,13,0,120,118,1,
		0,0,0,120,121,1,0,0,0,121,122,1,0,0,0,122,123,3,24,12,0,123,124,5,2,0,
		0,124,15,1,0,0,0,125,126,5,15,0,0,126,127,5,46,0,0,127,129,5,8,0,0,128,
		130,3,18,9,0,129,128,1,0,0,0,130,131,1,0,0,0,131,129,1,0,0,0,131,132,1,
		0,0,0,132,133,1,0,0,0,133,134,5,9,0,0,134,17,1,0,0,0,135,136,5,46,0,0,
		136,137,5,16,0,0,137,138,5,46,0,0,138,139,5,17,0,0,139,140,5,11,0,0,140,
		141,5,46,0,0,141,142,3,24,12,0,142,143,5,2,0,0,143,19,1,0,0,0,144,172,
		5,18,0,0,145,172,5,19,0,0,146,172,5,20,0,0,147,172,5,21,0,0,148,172,5,
		22,0,0,149,172,5,23,0,0,150,172,5,24,0,0,151,172,5,25,0,0,152,172,5,26,
		0,0,153,172,5,27,0,0,154,172,5,28,0,0,155,172,5,29,0,0,156,172,5,30,0,
		0,157,172,5,31,0,0,158,172,5,32,0,0,159,172,5,33,0,0,160,172,5,34,0,0,
		161,172,5,35,0,0,162,172,5,36,0,0,163,172,5,37,0,0,164,172,5,38,0,0,165,
		172,5,39,0,0,166,167,5,40,0,0,167,168,3,20,10,0,168,169,5,41,0,0,169,172,
		1,0,0,0,170,172,5,46,0,0,171,144,1,0,0,0,171,145,1,0,0,0,171,146,1,0,0,
		0,171,147,1,0,0,0,171,148,1,0,0,0,171,149,1,0,0,0,171,150,1,0,0,0,171,
		151,1,0,0,0,171,152,1,0,0,0,171,153,1,0,0,0,171,154,1,0,0,0,171,155,1,
		0,0,0,171,156,1,0,0,0,171,157,1,0,0,0,171,158,1,0,0,0,171,159,1,0,0,0,
		171,160,1,0,0,0,171,161,1,0,0,0,171,162,1,0,0,0,171,163,1,0,0,0,171,164,
		1,0,0,0,171,165,1,0,0,0,171,166,1,0,0,0,171,170,1,0,0,0,172,21,1,0,0,0,
		173,176,5,46,0,0,174,175,5,14,0,0,175,177,5,47,0,0,176,174,1,0,0,0,176,
		177,1,0,0,0,177,178,1,0,0,0,178,179,3,24,12,0,179,23,1,0,0,0,180,181,5,
		16,0,0,181,182,3,40,20,0,182,183,5,17,0,0,183,185,1,0,0,0,184,180,1,0,
		0,0,184,185,1,0,0,0,185,25,1,0,0,0,186,187,7,2,0,0,187,27,1,0,0,0,188,
		189,5,8,0,0,189,190,3,42,21,0,190,191,5,9,0,0,191,29,1,0,0,0,192,195,3,
		26,13,0,193,195,5,49,0,0,194,192,1,0,0,0,194,193,1,0,0,0,195,31,1,0,0,
		0,196,203,3,30,15,0,197,203,3,28,14,0,198,199,5,40,0,0,199,200,3,44,22,
		0,200,201,5,41,0,0,201,203,1,0,0,0,202,196,1,0,0,0,202,197,1,0,0,0,202,
		198,1,0,0,0,203,33,1,0,0,0,204,205,5,42,0,0,205,206,5,49,0,0,206,207,5,
		2,0,0,207,35,1,0,0,0,208,209,5,43,0,0,209,210,5,49,0,0,210,211,5,2,0,0,
		211,37,1,0,0,0,212,217,3,22,11,0,213,214,5,44,0,0,214,216,3,22,11,0,215,
		213,1,0,0,0,216,219,1,0,0,0,217,215,1,0,0,0,217,218,1,0,0,0,218,221,1,
		0,0,0,219,217,1,0,0,0,220,212,1,0,0,0,220,221,1,0,0,0,221,39,1,0,0,0,222,
		225,5,46,0,0,223,224,5,11,0,0,224,226,3,30,15,0,225,223,1,0,0,0,225,226,
		1,0,0,0,226,235,1,0,0,0,227,228,5,44,0,0,228,231,5,46,0,0,229,230,5,11,
		0,0,230,232,3,30,15,0,231,229,1,0,0,0,231,232,1,0,0,0,232,234,1,0,0,0,
		233,227,1,0,0,0,234,237,1,0,0,0,235,233,1,0,0,0,235,236,1,0,0,0,236,239,
		1,0,0,0,237,235,1,0,0,0,238,222,1,0,0,0,238,239,1,0,0,0,239,41,1,0,0,0,
		240,241,5,46,0,0,241,242,5,11,0,0,242,249,3,32,16,0,243,244,5,44,0,0,244,
		245,5,46,0,0,245,246,5,11,0,0,246,248,3,32,16,0,247,243,1,0,0,0,248,251,
		1,0,0,0,249,247,1,0,0,0,249,250,1,0,0,0,250,253,1,0,0,0,251,249,1,0,0,
		0,252,240,1,0,0,0,252,253,1,0,0,0,253,43,1,0,0,0,254,259,3,32,16,0,255,
		256,5,44,0,0,256,258,3,32,16,0,257,255,1,0,0,0,258,261,1,0,0,0,259,257,
		1,0,0,0,259,260,1,0,0,0,260,263,1,0,0,0,261,259,1,0,0,0,262,254,1,0,0,
		0,262,263,1,0,0,0,263,45,1,0,0,0,23,49,61,63,78,94,104,120,131,171,176,
		184,194,202,217,220,225,231,235,238,249,252,259,262
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
