// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct AuthReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static AuthReq GetRootAsAuthReq(ByteBuffer _bb) { return GetRootAsAuthReq(_bb, new AuthReq()); }
  public static AuthReq GetRootAsAuthReq(ByteBuffer _bb, AuthReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public AuthReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Account { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccountBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetAccountBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetAccountArray() { return __p.__vector_as_array<byte>(4); }
  public string Password { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPasswordBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetPasswordBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetPasswordArray() { return __p.__vector_as_array<byte>(6); }
  public int ServerId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<GenericBoson.Zozo.AuthReq> CreateAuthReq(FlatBufferBuilder builder,
      StringOffset accountOffset = default(StringOffset),
      StringOffset passwordOffset = default(StringOffset),
      int server_id = 0) {
    builder.StartTable(3);
    AuthReq.AddServerId(builder, server_id);
    AuthReq.AddPassword(builder, passwordOffset);
    AuthReq.AddAccount(builder, accountOffset);
    return AuthReq.EndAuthReq(builder);
  }

  public static void StartAuthReq(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddAccount(FlatBufferBuilder builder, StringOffset accountOffset) { builder.AddOffset(0, accountOffset.Value, 0); }
  public static void AddPassword(FlatBufferBuilder builder, StringOffset passwordOffset) { builder.AddOffset(1, passwordOffset.Value, 0); }
  public static void AddServerId(FlatBufferBuilder builder, int serverId) { builder.AddInt(2, serverId, 0); }
  public static Offset<GenericBoson.Zozo.AuthReq> EndAuthReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.AuthReq>(o);
  }
}


static public class AuthReqVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Account*/, false)
      && verifier.VerifyString(tablePos, 6 /*Password*/, false)
      && verifier.VerifyField(tablePos, 8 /*ServerId*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
