// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum CharacterState : uint
{
  None = 0,
  Playing = 1,
  LogedOff = 2,
};


}
