// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterPositionUpdateAck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterPositionUpdateAck GetRootAsCharacterPositionUpdateAck(ByteBuffer _bb) { return GetRootAsCharacterPositionUpdateAck(_bb, new CharacterPositionUpdateAck()); }
  public static CharacterPositionUpdateAck GetRootAsCharacterPositionUpdateAck(ByteBuffer _bb, CharacterPositionUpdateAck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterPositionUpdateAck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GenericBoson.Zozo.ResultCode ResultCode { get { int o = __p.__offset(4); return o != 0 ? (GenericBoson.Zozo.ResultCode)__p.bb.GetUint(o + __p.bb_pos) : GenericBoson.Zozo.ResultCode.Success; } }

  public static Offset<GenericBoson.Zozo.CharacterPositionUpdateAck> CreateCharacterPositionUpdateAck(FlatBufferBuilder builder,
      GenericBoson.Zozo.ResultCode result_code = GenericBoson.Zozo.ResultCode.Success) {
    builder.StartTable(1);
    CharacterPositionUpdateAck.AddResultCode(builder, result_code);
    return CharacterPositionUpdateAck.EndCharacterPositionUpdateAck(builder);
  }

  public static void StartCharacterPositionUpdateAck(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddResultCode(FlatBufferBuilder builder, GenericBoson.Zozo.ResultCode resultCode) { builder.AddUint(0, (uint)resultCode, 0); }
  public static Offset<GenericBoson.Zozo.CharacterPositionUpdateAck> EndCharacterPositionUpdateAck(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.CharacterPositionUpdateAck>(o);
  }
}


static public class CharacterPositionUpdateAckVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ResultCode*/, 4 /*GenericBoson.Zozo.ResultCode*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
