// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct CharacterListReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static CharacterListReq GetRootAsCharacterListReq(ByteBuffer _bb) { return GetRootAsCharacterListReq(_bb, new CharacterListReq()); }
  public static CharacterListReq GetRootAsCharacterListReq(ByteBuffer _bb, CharacterListReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public CharacterListReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Account { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetAccountBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetAccountBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetAccountArray() { return __p.__vector_as_array<byte>(4); }
  public string Token { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTokenBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTokenBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTokenArray() { return __p.__vector_as_array<byte>(6); }

  public static Offset<GenericBoson.Zozo.CharacterListReq> CreateCharacterListReq(FlatBufferBuilder builder,
      StringOffset accountOffset = default(StringOffset),
      StringOffset tokenOffset = default(StringOffset)) {
    builder.StartTable(2);
    CharacterListReq.AddToken(builder, tokenOffset);
    CharacterListReq.AddAccount(builder, accountOffset);
    return CharacterListReq.EndCharacterListReq(builder);
  }

  public static void StartCharacterListReq(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddAccount(FlatBufferBuilder builder, StringOffset accountOffset) { builder.AddOffset(0, accountOffset.Value, 0); }
  public static void AddToken(FlatBufferBuilder builder, StringOffset tokenOffset) { builder.AddOffset(1, tokenOffset.Value, 0); }
  public static Offset<GenericBoson.Zozo.CharacterListReq> EndCharacterListReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.CharacterListReq>(o);
  }
}


static public class CharacterListReqVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Account*/, false)
      && verifier.VerifyString(tablePos, 6 /*Token*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
