// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum Direction : sbyte
{
  None = 0,
  Up = 1,
  Down = 2,
  Right = 3,
  Left = 4,
};


}
