// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum GamePayload : byte
{
  NONE = 0,
  CharacterMoveReq = 1,
  CharacterMoveAck = 2,
};



static public class GamePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((GamePayload)typeId)
    {
      case GamePayload.CharacterMoveReq:
        result = GenericBoson.Zozo.CharacterMoveReqVerify.Verify(verifier, tablePos);
        break;
      case GamePayload.CharacterMoveAck:
        result = GenericBoson.Zozo.CharacterMoveAckVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
