// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum GamePayload : byte
{
  NONE = 0,
  CharacterListReq = 1,
  CharacterListAck = 2,
  CharacterSelectReq = 3,
  CharacterSelectAck = 4,
  CharacterPositionUpdateReq = 5,
  CharacterPositionUpdateAck = 6,
  CharacterCreateReq = 7,
  CharacterCreateAck = 8,
};



static public class GamePayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((GamePayload)typeId)
    {
      case GamePayload.CharacterListReq:
        result = GenericBoson.Zozo.CharacterListReqVerify.Verify(verifier, tablePos);
        break;
      case GamePayload.CharacterListAck:
        result = GenericBoson.Zozo.CharacterListAckVerify.Verify(verifier, tablePos);
        break;
      case GamePayload.CharacterSelectReq:
        result = GenericBoson.Zozo.CharacterSelectReqVerify.Verify(verifier, tablePos);
        break;
      case GamePayload.CharacterSelectAck:
        result = GenericBoson.Zozo.CharacterSelectAckVerify.Verify(verifier, tablePos);
        break;
      case GamePayload.CharacterPositionUpdateReq:
        result = GenericBoson.Zozo.CharacterPositionUpdateReqVerify.Verify(verifier, tablePos);
        break;
      case GamePayload.CharacterPositionUpdateAck:
        result = GenericBoson.Zozo.CharacterPositionUpdateAckVerify.Verify(verifier, tablePos);
        break;
      case GamePayload.CharacterCreateReq:
        result = GenericBoson.Zozo.CharacterCreateReqVerify.Verify(verifier, tablePos);
        break;
      case GamePayload.CharacterCreateAck:
        result = GenericBoson.Zozo.CharacterCreateAckVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
