// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ItemInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ItemInfo GetRootAsItemInfo(ByteBuffer _bb) { return GetRootAsItemInfo(_bb, new ItemInfo()); }
  public static ItemInfo GetRootAsItemInfo(ByteBuffer _bb, ItemInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ItemInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public long EffectId { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public GenericBoson.Zozo.ItemAttribute Attribute(int j) { int o = __p.__offset(10); return o != 0 ? (GenericBoson.Zozo.ItemAttribute)__p.bb.GetInt(__p.__vector(o) + j * 4) : (GenericBoson.Zozo.ItemAttribute)0; }
  public int AttributeLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<GenericBoson.Zozo.ItemAttribute> GetAttributeBytes() { return __p.__vector_as_span<GenericBoson.Zozo.ItemAttribute>(10, 4); }
#else
  public ArraySegment<byte>? GetAttributeBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public GenericBoson.Zozo.ItemAttribute[] GetAttributeArray() { int o = __p.__offset(10); if (o == 0) return null; int p = __p.__vector(o); int l = __p.__vector_len(o); GenericBoson.Zozo.ItemAttribute[] a = new GenericBoson.Zozo.ItemAttribute[l]; for (int i = 0; i < l; i++) { a[i] = (GenericBoson.Zozo.ItemAttribute)__p.bb.GetInt(p + i * 4); } return a; }
  public GenericBoson.Zozo.ItemType Type { get { int o = __p.__offset(12); return o != 0 ? (GenericBoson.Zozo.ItemType)__p.bb.GetInt(o + __p.bb_pos) : GenericBoson.Zozo.ItemType.None; } }

  public static Offset<GenericBoson.Zozo.ItemInfo> CreateItemInfo(FlatBufferBuilder builder,
      long id = 0,
      StringOffset nameOffset = default(StringOffset),
      long effect_id = 0,
      VectorOffset attributeOffset = default(VectorOffset),
      GenericBoson.Zozo.ItemType type = GenericBoson.Zozo.ItemType.None) {
    builder.StartTable(5);
    ItemInfo.AddEffectId(builder, effect_id);
    ItemInfo.AddId(builder, id);
    ItemInfo.AddType(builder, type);
    ItemInfo.AddAttribute(builder, attributeOffset);
    ItemInfo.AddName(builder, nameOffset);
    return ItemInfo.EndItemInfo(builder);
  }

  public static void StartItemInfo(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddId(FlatBufferBuilder builder, long id) { builder.AddLong(0, id, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddEffectId(FlatBufferBuilder builder, long effectId) { builder.AddLong(2, effectId, 0); }
  public static void AddAttribute(FlatBufferBuilder builder, VectorOffset attributeOffset) { builder.AddOffset(3, attributeOffset.Value, 0); }
  public static VectorOffset CreateAttributeVector(FlatBufferBuilder builder, GenericBoson.Zozo.ItemAttribute[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt((int)data[i]); return builder.EndVector(); }
  public static VectorOffset CreateAttributeVectorBlock(FlatBufferBuilder builder, GenericBoson.Zozo.ItemAttribute[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttributeVectorBlock(FlatBufferBuilder builder, ArraySegment<GenericBoson.Zozo.ItemAttribute> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateAttributeVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<GenericBoson.Zozo.ItemAttribute>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartAttributeVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddType(FlatBufferBuilder builder, GenericBoson.Zozo.ItemType type) { builder.AddInt(4, (int)type, 0); }
  public static Offset<GenericBoson.Zozo.ItemInfo> EndItemInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.ItemInfo>(o);
  }
}


static public class ItemInfoVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Id*/, 8 /*long*/, 8, false)
      && verifier.VerifyString(tablePos, 6 /*Name*/, false)
      && verifier.VerifyField(tablePos, 8 /*EffectId*/, 8 /*long*/, 8, false)
      && verifier.VerifyVectorOfData(tablePos, 10 /*Attribute*/, 4 /*GenericBoson.Zozo.ItemAttribute*/, false)
      && verifier.VerifyField(tablePos, 12 /*Type*/, 4 /*GenericBoson.Zozo.ItemType*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
