// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum ItemAttribute : int
{
  NonStackable = 1,
  Expairation = 2,
};


}
