// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum ItemType : int
{
  None = 0,
  Currency = 1,
  Consumable = 2,
  Weapon = 3,
  Armor = 4,
  Accessory = 5,
};


}
