// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LobbyMessage : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static LobbyMessage GetRootAsLobbyMessage(ByteBuffer _bb) { return GetRootAsLobbyMessage(_bb, new LobbyMessage()); }
  public static LobbyMessage GetRootAsLobbyMessage(ByteBuffer _bb, LobbyMessage obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyLobbyMessage(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, LobbyMessageVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LobbyMessage __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GenericBoson.Zozo.LobbyPayload PayloadType { get { int o = __p.__offset(4); return o != 0 ? (GenericBoson.Zozo.LobbyPayload)__p.bb.Get(o + __p.bb_pos) : GenericBoson.Zozo.LobbyPayload.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public GenericBoson.Zozo.AuthReq PayloadAsAuthReq() { return Payload<GenericBoson.Zozo.AuthReq>().Value; }
  public GenericBoson.Zozo.AuthAck PayloadAsAuthAck() { return Payload<GenericBoson.Zozo.AuthAck>().Value; }
  public GenericBoson.Zozo.LoginReq PayloadAsLoginReq() { return Payload<GenericBoson.Zozo.LoginReq>().Value; }
  public GenericBoson.Zozo.LoginAck PayloadAsLoginAck() { return Payload<GenericBoson.Zozo.LoginAck>().Value; }

  public static Offset<GenericBoson.Zozo.LobbyMessage> CreateLobbyMessage(FlatBufferBuilder builder,
      GenericBoson.Zozo.LobbyPayload payload_type = GenericBoson.Zozo.LobbyPayload.NONE,
      int payloadOffset = 0) {
    builder.StartTable(2);
    LobbyMessage.AddPayload(builder, payloadOffset);
    LobbyMessage.AddPayloadType(builder, payload_type);
    return LobbyMessage.EndLobbyMessage(builder);
  }

  public static void StartLobbyMessage(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPayloadType(FlatBufferBuilder builder, GenericBoson.Zozo.LobbyPayload payloadType) { builder.AddByte(0, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(1, payloadOffset, 0); }
  public static Offset<GenericBoson.Zozo.LobbyMessage> EndLobbyMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.LobbyMessage>(o);
  }
  public static void FinishLobbyMessageBuffer(FlatBufferBuilder builder, Offset<GenericBoson.Zozo.LobbyMessage> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedLobbyMessageBuffer(FlatBufferBuilder builder, Offset<GenericBoson.Zozo.LobbyMessage> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class LobbyMessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PayloadType*/, 1 /*GenericBoson.Zozo.LobbyPayload*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Payload*/, GenericBoson.Zozo.LobbyPayloadVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
