// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum LobbyPayload : byte
{
  NONE = 0,
  LoginReq = 1,
  LoginAck = 2,
};



static public class LobbyPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((LobbyPayload)typeId)
    {
      case LobbyPayload.LoginReq:
        result = GenericBoson.Zozo.LoginReqVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.LoginAck:
        result = GenericBoson.Zozo.LoginAckVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
