// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum LobbyPayload : byte
{
  NONE = 0,
  AuthReq = 1,
  AuthAck = 2,
  CharacterListReq = 3,
  CharacterListAck = 4,
  LoginReq = 5,
  LoginAck = 6,
};



static public class LobbyPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((LobbyPayload)typeId)
    {
      case LobbyPayload.AuthReq:
        result = GenericBoson.Zozo.AuthReqVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.AuthAck:
        result = GenericBoson.Zozo.AuthAckVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.CharacterListReq:
        result = GenericBoson.Zozo.CharacterListReqVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.CharacterListAck:
        result = GenericBoson.Zozo.CharacterListAckVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.LoginReq:
        result = GenericBoson.Zozo.LoginReqVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.LoginAck:
        result = GenericBoson.Zozo.LoginAckVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
