// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum LobbyPayload : byte
{
  NONE = 0,
  AuthReq = 1,
  AuthAck = 2,
  ServerListReq = 3,
  ServerListAck = 4,
};



static public class LobbyPayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((LobbyPayload)typeId)
    {
      case LobbyPayload.AuthReq:
        result = GenericBoson.Zozo.AuthReqVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.AuthAck:
        result = GenericBoson.Zozo.AuthAckVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.ServerListReq:
        result = GenericBoson.Zozo.ServerListReqVerify.Verify(verifier, tablePos);
        break;
      case LobbyPayload.ServerListAck:
        result = GenericBoson.Zozo.ServerListAckVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
