// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct LoginAck : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static LoginAck GetRootAsLoginAck(ByteBuffer _bb) { return GetRootAsLoginAck(_bb, new LoginAck()); }
  public static LoginAck GetRootAsLoginAck(ByteBuffer _bb, LoginAck obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public LoginAck __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GenericBoson.Zozo.ResultCode ResultCode { get { int o = __p.__offset(4); return o != 0 ? (GenericBoson.Zozo.ResultCode)__p.bb.GetUint(o + __p.bb_pos) : GenericBoson.Zozo.ResultCode.Success; } }
  public string Gameserverip { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGameserveripBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetGameserveripBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetGameserveripArray() { return __p.__vector_as_array<byte>(6); }
  public string Gameserverport { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetGameserverportBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetGameserverportBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetGameserverportArray() { return __p.__vector_as_array<byte>(8); }
  public string Token { get { int o = __p.__offset(10); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTokenBytes() { return __p.__vector_as_span<byte>(10, 1); }
#else
  public ArraySegment<byte>? GetTokenBytes() { return __p.__vector_as_arraysegment(10); }
#endif
  public byte[] GetTokenArray() { return __p.__vector_as_array<byte>(10); }

  public static Offset<GenericBoson.Zozo.LoginAck> CreateLoginAck(FlatBufferBuilder builder,
      GenericBoson.Zozo.ResultCode result_code = GenericBoson.Zozo.ResultCode.Success,
      StringOffset gameserveripOffset = default(StringOffset),
      StringOffset gameserverportOffset = default(StringOffset),
      StringOffset tokenOffset = default(StringOffset)) {
    builder.StartTable(4);
    LoginAck.AddToken(builder, tokenOffset);
    LoginAck.AddGameserverport(builder, gameserverportOffset);
    LoginAck.AddGameserverip(builder, gameserveripOffset);
    LoginAck.AddResultCode(builder, result_code);
    return LoginAck.EndLoginAck(builder);
  }

  public static void StartLoginAck(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddResultCode(FlatBufferBuilder builder, GenericBoson.Zozo.ResultCode resultCode) { builder.AddUint(0, (uint)resultCode, 0); }
  public static void AddGameserverip(FlatBufferBuilder builder, StringOffset gameserveripOffset) { builder.AddOffset(1, gameserveripOffset.Value, 0); }
  public static void AddGameserverport(FlatBufferBuilder builder, StringOffset gameserverportOffset) { builder.AddOffset(2, gameserverportOffset.Value, 0); }
  public static void AddToken(FlatBufferBuilder builder, StringOffset tokenOffset) { builder.AddOffset(3, tokenOffset.Value, 0); }
  public static Offset<GenericBoson.Zozo.LoginAck> EndLoginAck(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.LoginAck>(o);
  }
}


static public class LoginAckVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ResultCode*/, 4 /*GenericBoson.Zozo.ResultCode*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Gameserverip*/, false)
      && verifier.VerifyString(tablePos, 8 /*Gameserverport*/, false)
      && verifier.VerifyString(tablePos, 10 /*Token*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
