// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Message : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Message GetRootAsMessage(ByteBuffer _bb) { return GetRootAsMessage(_bb, new Message()); }
  public static Message GetRootAsMessage(ByteBuffer _bb, Message obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyMessage(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, MessageVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Message __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public GenericBoson.Zozo.Payload PayloadType { get { int o = __p.__offset(4); return o != 0 ? (GenericBoson.Zozo.Payload)__p.bb.Get(o + __p.bb_pos) : GenericBoson.Zozo.Payload.NONE; } }
  public TTable? Payload<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public GenericBoson.Zozo.LoginReq PayloadAsLoginReq() { return Payload<GenericBoson.Zozo.LoginReq>().Value; }
  public GenericBoson.Zozo.LoginAck PayloadAsLoginAck() { return Payload<GenericBoson.Zozo.LoginAck>().Value; }
  public GenericBoson.Zozo.CharacterMoveReq PayloadAsCharacterMoveReq() { return Payload<GenericBoson.Zozo.CharacterMoveReq>().Value; }
  public GenericBoson.Zozo.CharacterMoveAck PayloadAsCharacterMoveAck() { return Payload<GenericBoson.Zozo.CharacterMoveAck>().Value; }

  public static Offset<GenericBoson.Zozo.Message> CreateMessage(FlatBufferBuilder builder,
      GenericBoson.Zozo.Payload payload_type = GenericBoson.Zozo.Payload.NONE,
      int payloadOffset = 0) {
    builder.StartTable(2);
    Message.AddPayload(builder, payloadOffset);
    Message.AddPayloadType(builder, payload_type);
    return Message.EndMessage(builder);
  }

  public static void StartMessage(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddPayloadType(FlatBufferBuilder builder, GenericBoson.Zozo.Payload payloadType) { builder.AddByte(0, (byte)payloadType, 0); }
  public static void AddPayload(FlatBufferBuilder builder, int payloadOffset) { builder.AddOffset(1, payloadOffset, 0); }
  public static Offset<GenericBoson.Zozo.Message> EndMessage(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.Message>(o);
  }
  public static void FinishMessageBuffer(FlatBufferBuilder builder, Offset<GenericBoson.Zozo.Message> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedMessageBuffer(FlatBufferBuilder builder, Offset<GenericBoson.Zozo.Message> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class MessageVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*PayloadType*/, 1 /*GenericBoson.Zozo.Payload*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Payload*/, GenericBoson.Zozo.PayloadVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
