// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum Payload : byte
{
  NONE = 0,
  ConnectionReq = 1,
  ConnectionAck = 2,
  Ping = 3,
  Pong = 4,
  CharacterMoveReq = 5,
  CharacterMoveAck = 6,
};



static public class PayloadVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((Payload)typeId)
    {
      case Payload.ConnectionReq:
        result = GenericBoson.Zozo.ConnectionReqVerify.Verify(verifier, tablePos);
        break;
      case Payload.ConnectionAck:
        result = GenericBoson.Zozo.ConnectionAckVerify.Verify(verifier, tablePos);
        break;
      case Payload.Ping:
        result = GenericBoson.Zozo.PingVerify.Verify(verifier, tablePos);
        break;
      case Payload.Pong:
        result = GenericBoson.Zozo.PongVerify.Verify(verifier, tablePos);
        break;
      case Payload.CharacterMoveReq:
        result = GenericBoson.Zozo.CharacterMoveReqVerify.Verify(verifier, tablePos);
        break;
      case Payload.CharacterMoveAck:
        result = GenericBoson.Zozo.CharacterMoveAckVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
