// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum ResultCode : uint
{
  Success = 0,
  InvalidPacket = 1,
  NotAuthenticated = 2,
  ServerFull = 3,
  Banned = 4,
};


}
