// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ServerListReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ServerListReq GetRootAsServerListReq(ByteBuffer _bb) { return GetRootAsServerListReq(_bb, new ServerListReq()); }
  public static ServerListReq GetRootAsServerListReq(ByteBuffer _bb, ServerListReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ServerListReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartServerListReq(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<GenericBoson.Zozo.ServerListReq> EndServerListReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.ServerListReq>(o);
  }
}


static public class ServerListReqVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
