// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

public enum Stat : int
{
  None = 0,
  MeleeAttack = 1,
  MeleeDefence = 2,
  RangeAttack = 3,
  RangeDefence = 4,
  MagicAttack = 5,
  MagicDefence = 6,
  Agility = 7,
  Accuracy = 8,
  Speed = 9,
};


}
