// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct TryGetItemReq : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static TryGetItemReq GetRootAsTryGetItemReq(ByteBuffer _bb) { return GetRootAsTryGetItemReq(_bb, new TryGetItemReq()); }
  public static TryGetItemReq GetRootAsTryGetItemReq(ByteBuffer _bb, TryGetItemReq obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public TryGetItemReq __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string RootName { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRootNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetRootNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetRootNameArray() { return __p.__vector_as_array<byte>(4); }
  public string ItemName { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetItemNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetItemNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetItemNameArray() { return __p.__vector_as_array<byte>(6); }
  public int Count { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<GenericBoson.Zozo.TryGetItemReq> CreateTryGetItemReq(FlatBufferBuilder builder,
      StringOffset root_nameOffset = default(StringOffset),
      StringOffset item_nameOffset = default(StringOffset),
      int count = 0) {
    builder.StartTable(3);
    TryGetItemReq.AddCount(builder, count);
    TryGetItemReq.AddItemName(builder, item_nameOffset);
    TryGetItemReq.AddRootName(builder, root_nameOffset);
    return TryGetItemReq.EndTryGetItemReq(builder);
  }

  public static void StartTryGetItemReq(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddRootName(FlatBufferBuilder builder, StringOffset rootNameOffset) { builder.AddOffset(0, rootNameOffset.Value, 0); }
  public static void AddItemName(FlatBufferBuilder builder, StringOffset itemNameOffset) { builder.AddOffset(1, itemNameOffset.Value, 0); }
  public static void AddCount(FlatBufferBuilder builder, int count) { builder.AddInt(2, count, 0); }
  public static Offset<GenericBoson.Zozo.TryGetItemReq> EndTryGetItemReq(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<GenericBoson.Zozo.TryGetItemReq>(o);
  }
}


static public class TryGetItemReqVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*RootName*/, false)
      && verifier.VerifyString(tablePos, 6 /*ItemName*/, false)
      && verifier.VerifyField(tablePos, 8 /*Count*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
