// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace GenericBoson.Zozo
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Vector2D : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vector2D __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double X { get { return __p.bb.GetDouble(__p.bb_pos + 0); } }
  public double Y { get { return __p.bb.GetDouble(__p.bb_pos + 8); } }

  public static Offset<GenericBoson.Zozo.Vector2D> CreateVector2D(FlatBufferBuilder builder, double X, double Y) {
    builder.Prep(8, 16);
    builder.PutDouble(Y);
    builder.PutDouble(X);
    return new Offset<GenericBoson.Zozo.Vector2D>(builder.Offset);
  }
}


}
