// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONSTANT_GENERICBOSON_ZOZO_H_
#define FLATBUFFERS_GENERATED_CONSTANT_GENERICBOSON_ZOZO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace GenericBoson {
namespace Zozo {

enum MessageId : uint32_t {
  MessageId_None = 0,
  MessageId_ConnectionReq = 1,
  MessageId_ConnectionAck = 2,
  MessageId_Ping = 3,
  MessageId_Pong = 4,
  MessageId_CharacterMoveReq = 5,
  MessageId_CharacterMoveAck = 6,
  MessageId_MIN = MessageId_None,
  MessageId_MAX = MessageId_CharacterMoveAck
};

inline const MessageId (&EnumValuesMessageId())[7] {
  static const MessageId values[] = {
    MessageId_None,
    MessageId_ConnectionReq,
    MessageId_ConnectionAck,
    MessageId_Ping,
    MessageId_Pong,
    MessageId_CharacterMoveReq,
    MessageId_CharacterMoveAck
  };
  return values;
}

inline const char * const *EnumNamesMessageId() {
  static const char * const names[8] = {
    "None",
    "ConnectionReq",
    "ConnectionAck",
    "Ping",
    "Pong",
    "CharacterMoveReq",
    "CharacterMoveAck",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageId(MessageId e) {
  if (::flatbuffers::IsOutRange(e, MessageId_None, MessageId_CharacterMoveAck)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageId()[index];
}

enum ResultCode : uint32_t {
  ResultCode_Success = 0,
  ResultCode_InvalidPacket = 1,
  ResultCode_NotAuthenticated = 2,
  ResultCode_ServerFull = 3,
  ResultCode_Banned = 4,
  ResultCode_MIN = ResultCode_Success,
  ResultCode_MAX = ResultCode_Banned
};

inline const ResultCode (&EnumValuesResultCode())[5] {
  static const ResultCode values[] = {
    ResultCode_Success,
    ResultCode_InvalidPacket,
    ResultCode_NotAuthenticated,
    ResultCode_ServerFull,
    ResultCode_Banned
  };
  return values;
}

inline const char * const *EnumNamesResultCode() {
  static const char * const names[6] = {
    "Success",
    "InvalidPacket",
    "NotAuthenticated",
    "ServerFull",
    "Banned",
    nullptr
  };
  return names;
}

inline const char *EnumNameResultCode(ResultCode e) {
  if (::flatbuffers::IsOutRange(e, ResultCode_Success, ResultCode_Banned)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesResultCode()[index];
}

}  // namespace Zozo
}  // namespace GenericBoson

#endif  // FLATBUFFERS_GENERATED_CONSTANT_GENERICBOSON_ZOZO_H_
